/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// AccessToken : Access token response

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AccessToken {
    /// The access token
    #[serde(
        rename = "accessToken",
        skip_serializing_if = "Option::is_none"
    )]
    pub access_token: Option<String>,
    /// The refresh token
    #[serde(
        rename = "refreshToken",
        skip_serializing_if = "Option::is_none"
    )]
    pub refresh_token: Option<String>,
    /// The token type, as described in https://tools.ietf.org/html/rfc6749#section-7.1
    #[serde(
        rename = "tokenType",
        skip_serializing_if = "Option::is_none"
    )]
    pub token_type: Option<String>,
    /// The time in seconds from issuance at which the access token will expire
    #[serde(
        rename = "accessTokenExpiresInSeconds",
        skip_serializing_if = "Option::is_none"
    )]
    pub access_token_expires_in_seconds: Option<i64>,
    /// The scopes which this token has permission to use: Space delimited case sensitive Strings, as described in https://tools.ietf.org/html/rfc6749#section-3.3
    #[serde(rename = "scope", skip_serializing_if = "Option::is_none")]
    pub scope: Option<String>,
}

impl AccessToken {
    /// Access token response
    pub fn new() -> AccessToken {
        AccessToken {
            access_token: None,
            refresh_token: None,
            token_type: None,
            access_token_expires_in_seconds: None,
            scope: None,
        }
    }
}
