/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// AcceptedTermsRequest : Request to provide a collection of terms that have been accepted

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AcceptedTermsRequest {
    /// All of the terms that have been accepted
    #[serde(rename = "acceptedTerms")]
    pub accepted_terms: Vec<crate::models::AcceptedTerms>,
}

impl AcceptedTermsRequest {
    /// Request to provide a collection of terms that have been accepted
    pub fn new(
        accepted_terms: Vec<crate::models::AcceptedTerms>,
    ) -> AcceptedTermsRequest {
        AcceptedTermsRequest { accepted_terms }
    }
}
