/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// AcceptedTerms : The terms that are being accepted

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AcceptedTerms {
    /// The name of the terms document
    #[serde(rename = "termDocumentName")]
    pub term_document_name: String,
    /// The version of the terms document
    #[serde(rename = "version")]
    pub version: i32,
}

impl AcceptedTerms {
    /// The terms that are being accepted
    pub fn new(
        term_document_name: String,
        version: i32,
    ) -> AcceptedTerms {
        AcceptedTerms {
            term_document_name,
            version,
        }
    }
}
