/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// AccountHolderCreationResponse : Response after creating an account holder following a successful onboarding

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AccountHolderCreationResponse {
    /// The unique identifier of the account holder which has been created
    #[serde(rename = "accountHolderUid")]
    pub account_holder_uid: String,
    /// The unique identifier of the underlying account which has been created
    #[serde(rename = "accountUid")]
    pub account_uid: String,
    #[serde(
        rename = "authTokens",
        skip_serializing_if = "Option::is_none"
    )]
    pub auth_tokens: Option<Box<crate::models::AccessToken>>,
}

impl AccountHolderCreationResponse {
    /// Response after creating an account holder following a successful onboarding
    pub fn new(
        account_holder_uid: String,
        account_uid: String,
    ) -> AccountHolderCreationResponse {
        AccountHolderCreationResponse {
            account_holder_uid,
            account_uid,
            auth_tokens: None,
        }
    }
}
