/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// AccountHolder : Information about the account holder type

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AccountHolder {
    #[serde(
        rename = "accountHolderUid",
        skip_serializing_if = "Option::is_none"
    )]
    pub account_holder_uid: Option<String>,
    #[serde(
        rename = "accountHolderType",
        skip_serializing_if = "Option::is_none"
    )]
    pub account_holder_type: Option<AccountHolderType>,
}

impl AccountHolder {
    /// Information about the account holder type
    pub fn new() -> AccountHolder {
        AccountHolder {
            account_holder_uid: None,
            account_holder_type: None,
        }
    }
}

///
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
)]
pub enum AccountHolderType {
    #[serde(rename = "INDIVIDUAL")]
    INDIVIDUAL,
    #[serde(rename = "BUSINESS")]
    BUSINESS,
    #[serde(rename = "SOLE_TRADER")]
    SOLETRADER,
    #[serde(rename = "JOINT")]
    JOINT,
    #[serde(rename = "BANKING_AS_A_SERVICE")]
    BANKINGASASERVICE,
}

impl Default for AccountHolderType {
    fn default() -> AccountHolderType {
        Self::INDIVIDUAL
    }
}
