/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// AccountHolderName : Name of the account holder

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AccountHolderName {
    #[serde(
        rename = "accountHolderName",
        skip_serializing_if = "Option::is_none"
    )]
    pub account_holder_name: Option<String>,
}

impl AccountHolderName {
    /// Name of the account holder
    pub fn new() -> AccountHolderName {
        AccountHolderName {
            account_holder_name: None,
        }
    }
}
