/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// AccountIdentifiers : Bank account identifiers

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AccountIdentifiers {
    /// Identifier to uniquely identify the account at the bank
    #[serde(
        rename = "accountIdentifier",
        skip_serializing_if = "Option::is_none"
    )]
    pub account_identifier: Option<String>,
    /// Identifier to uniquely identify the bank
    #[serde(
        rename = "bankIdentifier",
        skip_serializing_if = "Option::is_none"
    )]
    pub bank_identifier: Option<String>,
    /// International identifier to uniquely identify the account at the bank
    #[serde(rename = "iban", skip_serializing_if = "Option::is_none")]
    pub iban: Option<String>,
    /// International identifier to uniquely identify the bank
    #[serde(rename = "bic", skip_serializing_if = "Option::is_none")]
    pub bic: Option<String>,
    #[serde(
        rename = "accountIdentifiers",
        skip_serializing_if = "Option::is_none"
    )]
    pub account_identifiers:
        Option<Vec<crate::models::AccountIdentifier>>,
}

impl AccountIdentifiers {
    /// Bank account identifiers
    pub fn new() -> AccountIdentifiers {
        AccountIdentifiers {
            account_identifier: None,
            bank_identifier: None,
            iban: None,
            bic: None,
            account_identifiers: None,
        }
    }
}
