/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// AccountStatementPeriod : A period for which an account statement is available

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AccountStatementPeriod {
    /// The period for which the statement is available
    #[serde(rename = "period")]
    pub period: String,
    /// Is the statement for this period partial
    #[serde(rename = "partial")]
    pub partial: bool,
    /// End timestamp for the period
    #[serde(
        rename = "endsAt",
        skip_serializing_if = "Option::is_none"
    )]
    pub ends_at: Option<String>,
}

impl AccountStatementPeriod {
    /// A period for which an account statement is available
    pub fn new(
        period: String,
        partial: bool,
    ) -> AccountStatementPeriod {
        AccountStatementPeriod {
            period,
            partial,
            ends_at: None,
        }
    }
}
