/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// AccountStatementPeriods : A list of periods for which an account statement is available

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AccountStatementPeriods {
    #[serde(
        rename = "periods",
        skip_serializing_if = "Option::is_none"
    )]
    pub periods: Option<Vec<crate::models::AccountStatementPeriod>>,
}

impl AccountStatementPeriods {
    /// A list of periods for which an account statement is available
    pub fn new() -> AccountStatementPeriods {
        AccountStatementPeriods { periods: None }
    }
}
