/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// AddressUpdateRequest : Address update request

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AddressUpdateRequest {
    #[serde(rename = "line1")]
    pub line1: String,
    #[serde(rename = "line2", skip_serializing_if = "Option::is_none")]
    pub line2: Option<String>,
    #[serde(rename = "line3", skip_serializing_if = "Option::is_none")]
    pub line3: Option<String>,
    #[serde(rename = "postTown")]
    pub post_town: String,
    #[serde(rename = "postCode")]
    pub post_code: String,
    /// Country code in ISO 3166-1 alpha-2. NB GB is the official country code for the UK. UK is not the officially assigned code, and so is not valid
    #[serde(rename = "countryCode")]
    pub country_code: String,
    /// The UDPRN of the property
    #[serde(rename = "udprn", skip_serializing_if = "Option::is_none")]
    pub udprn: Option<String>,
    /// The UMPRN of the property
    #[serde(rename = "umprn", skip_serializing_if = "Option::is_none")]
    pub umprn: Option<String>,
    /// Date the account holder's residency at this address started
    #[serde(rename = "from")]
    pub from: String,
}

impl AddressUpdateRequest {
    /// Address update request
    pub fn new(
        line1: String,
        post_town: String,
        post_code: String,
        country_code: String,
        from: String,
    ) -> AddressUpdateRequest {
        AddressUpdateRequest {
            line1,
            line2: None,
            line3: None,
            post_town,
            post_code,
            country_code,
            udprn: None,
            umprn: None,
            from,
        }
    }
}
