/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// AssociatedFeedRoundUp : Round up details associated with a feed item

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AssociatedFeedRoundUp {
    /// Unique identifier of associated category
    #[serde(
        rename = "goalCategoryUid",
        skip_serializing_if = "Option::is_none"
    )]
    pub goal_category_uid: Option<String>,
    #[serde(
        rename = "amount",
        skip_serializing_if = "Option::is_none"
    )]
    pub amount: Option<Box<crate::models::CurrencyAndAmount>>,
}

impl AssociatedFeedRoundUp {
    /// Round up details associated with a feed item
    pub fn new() -> AssociatedFeedRoundUp {
        AssociatedFeedRoundUp {
            goal_category_uid: None,
            amount: None,
        }
    }
}
