/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// BatchPaymentDetails : The details of the batch payment this is part of, if it is

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BatchPaymentDetails {
    /// The unique identifier for the batch payment
    #[serde(
        rename = "batchPaymentUid",
        skip_serializing_if = "Option::is_none"
    )]
    pub batch_payment_uid: Option<String>,
    /// The type of the batch payment itself
    #[serde(
        rename = "batchPaymentType",
        skip_serializing_if = "Option::is_none"
    )]
    pub batch_payment_type: Option<BatchPaymentType>,
}

impl BatchPaymentDetails {
    /// The details of the batch payment this is part of, if it is
    pub fn new() -> BatchPaymentDetails {
        BatchPaymentDetails {
            batch_payment_uid: None,
            batch_payment_type: None,
        }
    }
}

/// The type of the batch payment itself
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
)]
pub enum BatchPaymentType {
    #[serde(rename = "BULK_PAYMENT")]
    BULKPAYMENT,
}

impl Default for BatchPaymentType {
    fn default() -> BatchPaymentType {
        Self::BULKPAYMENT
    }
}
