/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// Cards : Wrapper around multiple cards

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Cards {
    #[serde(rename = "cards")]
    pub cards: Vec<crate::models::Card>,
}

impl Cards {
    /// Wrapper around multiple cards
    pub fn new(cards: Vec<crate::models::Card>) -> Cards {
        Cards { cards }
    }
}
