/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// ChangeMobilePhoneNumberRequest : Request to update an account holder mobile phone number

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ChangeMobilePhoneNumberRequest {
    /// Details of the new mobile phone number
    #[serde(rename = "mobilePhoneNumber")]
    pub mobile_phone_number: String,
    /// Confirmation of the mobile phone number validity
    #[serde(rename = "mobilePhoneNumberVerified")]
    pub mobile_phone_number_verified: bool,
}

impl ChangeMobilePhoneNumberRequest {
    /// Request to update an account holder mobile phone number
    pub fn new(
        mobile_phone_number: String,
        mobile_phone_number_verified: bool,
    ) -> ChangeMobilePhoneNumberRequest {
        ChangeMobilePhoneNumberRequest {
            mobile_phone_number,
            mobile_phone_number_verified,
        }
    }
}
