/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// ChangeEmailRequest : Request to update an account holder email

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ChangeEmailRequest {
    /// Details of the new email address
    #[serde(rename = "email")]
    pub email: String,
    /// Confirmation of the email address validity
    #[serde(
        rename = "emailVerified",
        skip_serializing_if = "Option::is_none"
    )]
    pub email_verified: Option<bool>,
}

impl ChangeEmailRequest {
    /// Request to update an account holder email
    pub fn new(email: String) -> ChangeEmailRequest {
        ChangeEmailRequest {
            email,
            email_verified: None,
        }
    }
}
