/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// ChangeAddressRequest : Request to update an account holder address

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ChangeAddressRequest {
    #[serde(rename = "addressRequest")]
    pub address_request: Box<crate::models::AddressRequest>,
    /// Confirmation of the address validity
    #[serde(
        rename = "addressVerified",
        skip_serializing_if = "Option::is_none"
    )]
    pub address_verified: Option<bool>,
}

impl ChangeAddressRequest {
    /// Request to update an account holder address
    pub fn new(
        address_request: crate::models::AddressRequest,
    ) -> ChangeAddressRequest {
        ChangeAddressRequest {
            address_request: Box::new(address_request),
            address_verified: None,
        }
    }
}
