/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// ConfirmVideoUploadRequest : Request to confirm that a video has been uploaded

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ConfirmVideoUploadRequest {
    /// The UID of the phrase to be included in the video
    #[serde(rename = "phraseUid")]
    pub phrase_uid: String,
    /// The filename of the video that was uploaded
    #[serde(rename = "filename")]
    pub filename: String,
}

impl ConfirmVideoUploadRequest {
    /// Request to confirm that a video has been uploaded
    pub fn new(
        phrase_uid: String,
        filename: String,
    ) -> ConfirmVideoUploadRequest {
        ConfirmVideoUploadRequest {
            phrase_uid,
            filename,
        }
    }
}
