/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ConfirmationOfFundsResponse {
    /// True if requested amount is available to spend
    #[serde(
        rename = "requestedAmountAvailableToSpend",
        skip_serializing_if = "Option::is_none"
    )]
    pub requested_amount_available_to_spend: Option<bool>,
    /// True if spending the requested amount would put the account in overdraft
    #[serde(
        rename = "accountWouldBeInOverdraftIfRequestedAmountSpent",
        skip_serializing_if = "Option::is_none"
    )]
    pub account_would_be_in_overdraft_if_requested_amount_spent:
        Option<bool>,
}

impl ConfirmationOfFundsResponse {
    pub fn new() -> ConfirmationOfFundsResponse {
        ConfirmationOfFundsResponse {
            requested_amount_available_to_spend: None,
            account_would_be_in_overdraft_if_requested_amount_spent:
                None,
        }
    }
}
