/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ConfirmUploadRequestContentType {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
    #[serde(
        rename = "subtype",
        skip_serializing_if = "Option::is_none"
    )]
    pub subtype: Option<String>,
    #[serde(
        rename = "parameters",
        skip_serializing_if = "Option::is_none"
    )]
    pub parameters: Option<::std::collections::HashMap<String, String>>,
    #[serde(
        rename = "wildcardType",
        skip_serializing_if = "Option::is_none"
    )]
    pub wildcard_type: Option<bool>,
    #[serde(
        rename = "wildcardSubtype",
        skip_serializing_if = "Option::is_none"
    )]
    pub wildcard_subtype: Option<bool>,
}

impl ConfirmUploadRequestContentType {
    pub fn new() -> ConfirmUploadRequestContentType {
        ConfirmUploadRequestContentType {
            _type: None,
            subtype: None,
            parameters: None,
            wildcard_type: None,
            wildcard_subtype: None,
        }
    }
}
