/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// CreateOrUpdateSavingsGoalResponseV2 : Response after attempting to create a savings goal

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateOrUpdateSavingsGoalResponseV2 {
    /// Unique identifier of the savings goal
    #[serde(
        rename = "savingsGoalUid",
        skip_serializing_if = "Option::is_none"
    )]
    pub savings_goal_uid: Option<String>,
    /// True if the method completed successfully
    #[serde(
        rename = "success",
        skip_serializing_if = "Option::is_none"
    )]
    pub success: Option<bool>,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<Vec<crate::models::ErrorDetail>>,
    #[serde(
        rename = "errors",
        skip_serializing_if = "Option::is_none"
    )]
    pub errors: Option<Vec<crate::models::ErrorDetail>>,
}

impl CreateOrUpdateSavingsGoalResponseV2 {
    /// Response after attempting to create a savings goal
    pub fn new() -> CreateOrUpdateSavingsGoalResponseV2 {
        CreateOrUpdateSavingsGoalResponseV2 {
            savings_goal_uid: None,
            success: None,
            error: None,
            errors: None,
        }
    }
}
