/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// CreateStandingOrderResponse : Response after attempting to create a standing order

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateStandingOrderResponse {
    /// The uid of the payment order created by the standing order. N.B. this will not be the uid of any payment which is created by the standing order
    #[serde(
        rename = "paymentOrderUid",
        skip_serializing_if = "Option::is_none"
    )]
    pub payment_order_uid: Option<String>,
}

impl CreateStandingOrderResponse {
    /// Response after attempting to create a standing order
    pub fn new() -> CreateStandingOrderResponse {
        CreateStandingOrderResponse {
            payment_order_uid: None,
        }
    }
}
