/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// CurrencyFlag : Whether spending is enabled on this card for the specified currency

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CurrencyFlag {
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "currency")]
    pub currency: String,
}

impl CurrencyFlag {
    /// Whether spending is enabled on this card for the specified currency
    pub fn new(enabled: bool, currency: String) -> CurrencyFlag {
        CurrencyFlag { enabled, currency }
    }
}
