/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// DefundingPaymentRecipientRequest : The desired payment recipient. The payment recipient must be present

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DefundingPaymentRecipientRequest {
    #[serde(rename = "payeeType")]
    pub payee_type: PayeeType,
    /// The country code for the account (ISO 3166-1 alpha-2)
    #[serde(rename = "countryCode")]
    pub country_code: String,
    #[serde(rename = "accountIdentifier")]
    pub account_identifier: String,
    #[serde(rename = "bankIdentifier")]
    pub bank_identifier: String,
    #[serde(rename = "bankIdentifierType")]
    pub bank_identifier_type: BankIdentifierType,
}

impl DefundingPaymentRecipientRequest {
    /// The desired payment recipient. The payment recipient must be present
    pub fn new(
        payee_type: PayeeType,
        country_code: String,
        account_identifier: String,
        bank_identifier: String,
        bank_identifier_type: BankIdentifierType,
    ) -> DefundingPaymentRecipientRequest {
        DefundingPaymentRecipientRequest {
            payee_type,
            country_code,
            account_identifier,
            bank_identifier,
            bank_identifier_type,
        }
    }
}

///
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
)]
pub enum PayeeType {
    #[serde(rename = "BUSINESS")]
    BUSINESS,
    #[serde(rename = "INDIVIDUAL")]
    INDIVIDUAL,
}

impl Default for PayeeType {
    fn default() -> PayeeType {
        Self::BUSINESS
    }
}
///
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
)]
pub enum BankIdentifierType {
    #[serde(rename = "SORT_CODE")]
    SORTCODE,
    #[serde(rename = "SWIFT")]
    SWIFT,
    #[serde(rename = "IBAN")]
    IBAN,
    #[serde(rename = "ABA")]
    ABA,
    #[serde(rename = "ABA_WIRE")]
    ABAWIRE,
    #[serde(rename = "ABA_ACH")]
    ABAACH,
    #[serde(rename = "BSB")]
    BSB,
}

impl Default for BankIdentifierType {
    fn default() -> BankIdentifierType {
        Self::SORTCODE
    }
}
