/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// DirectDebitPaymentsResponse : Transaction history for a direct debit

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DirectDebitPaymentsResponse {
    /// List of processed direct debit mandate payments
    #[serde(rename = "directDebitPayments")]
    pub direct_debit_payments: Vec<crate::models::DirectDebitPayment>,
}

impl DirectDebitPaymentsResponse {
    /// Transaction history for a direct debit
    pub fn new(
        direct_debit_payments: Vec<crate::models::DirectDebitPayment>,
    ) -> DirectDebitPaymentsResponse {
        DirectDebitPaymentsResponse {
            direct_debit_payments,
        }
    }
}
