/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// DirectDebitPayment : A previous Direct Debit payment

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DirectDebitPayment {
    #[serde(
        rename = "paymentAmount",
        skip_serializing_if = "Option::is_none"
    )]
    pub payment_amount: Option<Box<crate::models::CurrencyAndAmount>>,
    /// Date when direct debit payment was created
    #[serde(
        rename = "createdAt",
        skip_serializing_if = "Option::is_none"
    )]
    pub created_at: Option<String>,
}

impl DirectDebitPayment {
    /// A previous Direct Debit payment
    pub fn new() -> DirectDebitPayment {
        DirectDebitPayment {
            payment_amount: None,
            created_at: None,
        }
    }
}
