/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// DirectDebitMandatesV2 : List of mandates

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DirectDebitMandatesV2 {
    #[serde(
        rename = "mandates",
        skip_serializing_if = "Option::is_none"
    )]
    pub mandates: Option<Vec<crate::models::DirectDebitMandateV2>>,
}

impl DirectDebitMandatesV2 {
    /// List of mandates
    pub fn new() -> DirectDebitMandatesV2 {
        DirectDebitMandatesV2 { mandates: None }
    }
}
