/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// EmploymentSectorsResponse : Response containing all employment sectors and their regulation status

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EmploymentSectorsResponse {
    #[serde(
        rename = "employmentSectors",
        skip_serializing_if = "Option::is_none"
    )]
    pub employment_sectors:
        Option<Vec<crate::models::EmploymentSectorRegulationStatus>>,
    #[serde(
        rename = "employmentSectorRoles",
        skip_serializing_if = "Option::is_none"
    )]
    pub employment_sector_roles: Option<Vec<EmploymentSectorRoles>>,
}

impl EmploymentSectorsResponse {
    /// Response containing all employment sectors and their regulation status
    pub fn new() -> EmploymentSectorsResponse {
        EmploymentSectorsResponse {
            employment_sectors: None,
            employment_sector_roles: None,
        }
    }
}

///
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
)]
pub enum EmploymentSectorRoles {
    #[serde(rename = "EMPLOYEE")]
    EMPLOYEE,
    #[serde(rename = "TEAM_LEADER_MANAGEMENT")]
    TEAMLEADERMANAGEMENT,
    #[serde(rename = "SENIOR_MANAGER")]
    SENIORMANAGER,
    #[serde(rename = "EXECUTIVE_DIRECTOR")]
    EXECUTIVEDIRECTOR,
    #[serde(rename = "SELF_EMPLOYED")]
    SELFEMPLOYED,
}

impl Default for EmploymentSectorRoles {
    fn default() -> EmploymentSectorRoles {
        Self::EMPLOYEE
    }
}
