/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// EmploymentSectorRegulationStatus : Employment sector and regulation status

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EmploymentSectorRegulationStatus {
    /// Employment sector
    #[serde(
        rename = "employmentSector",
        skip_serializing_if = "Option::is_none"
    )]
    pub employment_sector: Option<EmploymentSector>,
    /// Regulation status
    #[serde(
        rename = "regulationStatus",
        skip_serializing_if = "Option::is_none"
    )]
    pub regulation_status: Option<RegulationStatus>,
}

impl EmploymentSectorRegulationStatus {
    /// Employment sector and regulation status
    pub fn new() -> EmploymentSectorRegulationStatus {
        EmploymentSectorRegulationStatus {
            employment_sector: None,
            regulation_status: None,
        }
    }
}

/// Employment sector
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
)]
pub enum EmploymentSector {
    #[serde(rename = "ACCOUNTANCY_AND_BOOKKEEPING")]
    ACCOUNTANCYANDBOOKKEEPING,
    #[serde(rename = "ADULT_INDUSTRY")]
    ADULTINDUSTRY,
    #[serde(rename = "ANIMALS")]
    ANIMALS,
    #[serde(rename = "ANIMAL_CARE")]
    ANIMALCARE,
    #[serde(rename = "ARCHITECT_STRUCTURAL_ENGINEER_OR_SURVEYOR")]
    ARCHITECTSTRUCTURALENGINEERORSURVEYOR,
    #[serde(rename = "ARMED_FORCES")]
    ARMEDFORCES,
    #[serde(rename = "ARTS_CULTURE_AND_HUMANITIES")]
    ARTSCULTUREANDHUMANITIES,
    #[serde(rename = "ASSET_MANAGEMENT")]
    ASSETMANAGEMENT,
    #[serde(rename = "AT_HOME_SERVICES")]
    ATHOMESERVICES,
    #[serde(rename = "BANKING_INVESTMENT")]
    BANKINGINVESTMENT,
    #[serde(rename = "BICYCLE_SHOPS")]
    BICYCLESHOPS,
    #[serde(rename = "BUSINESS_SERVICES")]
    BUSINESSSERVICES,
    #[serde(rename = "CARPENTRY_TRADE")]
    CARPENTRYTRADE,
    #[serde(rename = "CAR_WASHING")]
    CARWASHING,
    #[serde(rename = "CATERING")]
    CATERING,
    #[serde(rename = "CHILDMINDER")]
    CHILDMINDER,
    #[serde(rename = "CHILDRENS_ACTIVITIES")]
    CHILDRENSACTIVITIES,
    #[serde(rename = "CHILDREN_YOUTH_AND_FAMILY")]
    CHILDRENYOUTHANDFAMILY,
    #[serde(rename = "CHIROPRACTOR_OR_OSTEOPATH")]
    CHIROPRACTOROROSTEOPATH,
    #[serde(rename = "CLASS_INSTRUCTOR")]
    CLASSINSTRUCTOR,
    #[serde(rename = "CLEANING")]
    CLEANING,
    #[serde(rename = "COMMUNITY_DEVELOPMENT")]
    COMMUNITYDEVELOPMENT,
    #[serde(rename = "COMPLIMENTARY_AND_ALTERNATIVE_MEDICINE")]
    COMPLIMENTARYANDALTERNATIVEMEDICINE,
    #[serde(rename = "CONSTRUCTION_SUPPLIER")]
    CONSTRUCTIONSUPPLIER,
    #[serde(rename = "CONSTRUCTION_TRADES_AND_CLEANING_OTHER")]
    CONSTRUCTIONTRADESANDCLEANINGOTHER,
    #[serde(rename = "CROP_FARMING")]
    CROPFARMING,
    #[serde(rename = "DECORATING")]
    DECORATING,
    #[serde(rename = "DENTAL")]
    DENTAL,
    #[serde(rename = "DERIVATIVES_TRADING")]
    DERIVATIVESTRADING,
    #[serde(rename = "DIGITAL_CONTENT_OR_GAMES")]
    DIGITALCONTENTORGAMES,
    #[serde(rename = "DOCTOR_NURSE_OR_MIDWIFE")]
    DOCTORNURSEORMIDWIFE,
    #[serde(rename = "EDUCATION")]
    EDUCATION,
    #[serde(rename = "EDUCATION_AND_SKILLS_OTHER")]
    EDUCATIONANDSKILLSOTHER,
    #[serde(rename = "ELECTRICIAN")]
    ELECTRICIAN,
    #[serde(rename = "ENTERTAINERS_AND_DJS")]
    ENTERTAINERSANDDJS,
    #[serde(rename = "ENTERTAINMENT_AND_TRAVEL_OTHER")]
    ENTERTAINMENTANDTRAVELOTHER,
    #[serde(rename = "ENVIRONMENT")]
    ENVIRONMENT,
    #[serde(rename = "EQUESTRIAN")]
    EQUESTRIAN,
    #[serde(rename = "EQUITIES_TRADING")]
    EQUITIESTRADING,
    #[serde(rename = "ESTATE_AGENT")]
    ESTATEAGENT,
    #[serde(rename = "EVENTS_AND_WEDDINGS")]
    EVENTSANDWEDDINGS,
    #[serde(rename = "EVENTS_PRODUCTS")]
    EVENTSPRODUCTS,
    #[serde(rename = "EVENTS_STAFFING_AND_SERVICES")]
    EVENTSSTAFFINGANDSERVICES,
    #[serde(rename = "EXERCISE_AND_FITNESS_OTHER")]
    EXERCISEANDFITNESSOTHER,
    #[serde(rename = "FINANCIAL_OR_INVESTMENT_ADVICE")]
    FINANCIALORINVESTMENTADVICE,
    #[serde(rename = "FIREARMS_MILITARY_GOODS")]
    FIREARMSMILITARYGOODS,
    #[serde(rename = "FOOD_OR_DRINK_PRODUCTION")]
    FOODORDRINKPRODUCTION,
    #[serde(rename = "FORESTRY")]
    FORESTRY,
    #[serde(rename = "FUND_MANAGEMENT")]
    FUNDMANAGEMENT,
    #[serde(rename = "FUND_MANAGER")]
    FUNDMANAGER,
    #[serde(rename = "FX_TRADING")]
    FXTRADING,
    #[serde(rename = "GARDENING_AND_TREE_SURGERY")]
    GARDENINGANDTREESURGERY,
    #[serde(rename = "GAS_AND_HEATING")]
    GASANDHEATING,
    #[serde(rename = "GENERAL_CONTRACTOR")]
    GENERALCONTRACTOR,
    #[serde(rename = "GRAPHIC_DESIGN_AND_ILLUSTRATION")]
    GRAPHICDESIGNANDILLUSTRATION,
    #[serde(rename = "GYM_OPERATOR")]
    GYMOPERATOR,
    #[serde(rename = "HAULAGE_FIRMS")]
    HAULAGEFIRMS,
    #[serde(rename = "HEALTH_AND_DISEASE")]
    HEALTHANDDISEASE,
    #[serde(rename = "HEALTH_AND_SOCIAL_CARE_OTHER")]
    HEALTHANDSOCIALCAREOTHER,
    #[serde(rename = "HGV_OR_BUS_OR_COACH_DRIVER")]
    HGVORBUSORCOACHDRIVER,
    #[serde(rename = "HOLIDAY_OR_SHORT_TERM_LETS")]
    HOLIDAYORSHORTTERMLETS,
    #[serde(rename = "HOMELESSNESS")]
    HOMELESSNESS,
    #[serde(rename = "HOME_DELIVERY_AND_COURIER_FIRMS")]
    HOMEDELIVERYANDCOURIERFIRMS,
    #[serde(rename = "HORTICULTURE_OR_PLANT_NURSERY")]
    HORTICULTUREORPLANTNURSERY,
    #[serde(rename = "HUMAN_AND_CIVIL_RIGHTS")]
    HUMANANDCIVILRIGHTS,
    #[serde(rename = "ILLEGAL_OR_UNLICENSED_DRUGS")]
    ILLEGALORUNLICENSEDDRUGS,
    #[serde(rename = "INDUSTRIAL_ENGINEER")]
    INDUSTRIALENGINEER,
    #[serde(rename = "INSOLVENCY_PRACTITIONER")]
    INSOLVENCYPRACTITIONER,
    #[serde(rename = "INTERIOR_DESIGN")]
    INTERIORDESIGN,
    #[serde(rename = "INTERNATIONAL")]
    INTERNATIONAL,
    #[serde(rename = "INTERNATIONAL_FINANCE")]
    INTERNATIONALFINANCE,
    #[serde(rename = "INVESTMENT_BANK")]
    INVESTMENTBANK,
    #[serde(rename = "INVESTMENT_BANKING")]
    INVESTMENTBANKING,
    #[serde(rename = "INVESTMENT_DEAL_ARRANGEMENTS")]
    INVESTMENTDEALARRANGEMENTS,
    #[serde(rename = "INVESTMENT_MANAGEMENT")]
    INVESTMENTMANAGEMENT,
    #[serde(rename = "JEWELLERY_PRECIOUS_STONES_OR_METALS")]
    JEWELLERYPRECIOUSSTONESORMETALS,
    #[serde(rename = "LEASEHOLD_OR_FREEHOLD")]
    LEASEHOLDORFREEHOLD,
    #[serde(rename = "LEGAL")]
    LEGAL,
    #[serde(rename = "LICENSED_FOOD_VENUE")]
    LICENSEDFOODVENUE,
    #[serde(rename = "LICENSED_RETAIL")]
    LICENSEDRETAIL,
    #[serde(rename = "LIVESTOCK_FARMING")]
    LIVESTOCKFARMING,
    #[serde(rename = "LODGING_AND_ACCOMMODATION")]
    LODGINGANDACCOMMODATION,
    #[serde(rename = "MANAGEMENT_CONSULTANCY")]
    MANAGEMENTCONSULTANCY,
    #[serde(rename = "MANUFACTURING")]
    MANUFACTURING,
    #[serde(rename = "MANUFACTURING_RND_AND_AGRICULTURE_OTHER")]
    MANUFACTURINGRNDANDAGRICULTUREOTHER,
    #[serde(rename = "MARKETING_ADVERTISING_AND_DESIGN")]
    MARKETINGADVERTISINGANDDESIGN,
    #[serde(rename = "MARKET_MAKER")]
    MARKETMAKER,
    #[serde(rename = "MEDICAL_EQUIPMENT_AND_SUPPLIERS")]
    MEDICALEQUIPMENTANDSUPPLIERS,
    #[serde(rename = "MENTAL_HEALTH_AND_COUNSELLING")]
    MENTALHEALTHANDCOUNSELLING,
    #[serde(rename = "MERCHANT_BANKING")]
    MERCHANTBANKING,
    #[serde(rename = "MINIBUS_OR_COACH_OPERATOR")]
    MINIBUSORCOACHOPERATOR,
    #[serde(rename = "MORTGAGE_BROKERS")]
    MORTGAGEBROKERS,
    #[serde(rename = "MUSICIAN_OR_GROUPS")]
    MUSICIANORGROUPS,
    #[serde(rename = "MUSIC_TEACHERS")]
    MUSICTEACHERS,
    #[serde(rename = "NAIL_PARLOUR")]
    NAILPARLOUR,
    #[serde(rename = "NANNY_OR_AU_PAIR")]
    NANNYORAUPAIR,
    #[serde(rename = "NEWSAGENTS_CONVENIENCE_STORES")]
    NEWSAGENTSCONVENIENCESTORES,
    #[serde(rename = "NEW_CARS_OR_VEHICLE_SALES")]
    NEWCARSORVEHICLESALES,
    #[serde(rename = "NHS")]
    NHS,
    #[serde(rename = "NON_PROFIT_OTHER")]
    NONPROFITOTHER,
    #[serde(rename = "NURSERY")]
    NURSERY,
    #[serde(rename = "NUTRITION_AND_DIET")]
    NUTRITIONANDDIET,
    #[serde(rename = "OPTICIAN")]
    OPTICIAN,
    #[serde(rename = "OTHER_MEDICAL_THERAPY")]
    OTHERMEDICALTHERAPY,
    #[serde(rename = "OTHER_PROFESSIONAL_DRIVER")]
    OTHERPROFESSIONALDRIVER,
    #[serde(rename = "PAYROLL_PROVIDER")]
    PAYROLLPROVIDER,
    #[serde(rename = "PERSONAL_AND_SOCIAL_CARE")]
    PERSONALANDSOCIALCARE,
    #[serde(rename = "PERSONAL_TRAINER")]
    PERSONALTRAINER,
    #[serde(rename = "PERSONAL_TUTOR")]
    PERSONALTUTOR,
    #[serde(rename = "PHARMACY")]
    PHARMACY,
    #[serde(rename = "PHOTOGRAPHY")]
    PHOTOGRAPHY,
    #[serde(rename = "PHYSIOTHERAPIST")]
    PHYSIOTHERAPIST,
    #[serde(rename = "PLUMBER")]
    PLUMBER,
    #[serde(rename = "PODIATRIST")]
    PODIATRIST,
    #[serde(rename = "PRIVATE_HEALTHCARE")]
    PRIVATEHEALTHCARE,
    #[serde(rename = "PROBATE_ESTATE_MANAGEMENT")]
    PROBATEESTATEMANAGEMENT,
    #[serde(rename = "PROFESSIONAL_SERVICES_OTHER")]
    PROFESSIONALSERVICESOTHER,
    #[serde(rename = "PROFESSIONAL_TRAINER")]
    PROFESSIONALTRAINER,
    #[serde(rename = "PROJECT_MANAGEMENT")]
    PROJECTMANAGEMENT,
    #[serde(rename = "PROMOTION_AND_PUBLISHING")]
    PROMOTIONANDPUBLISHING,
    #[serde(rename = "PROPERTY_INVESTMENT_FUND")]
    PROPERTYINVESTMENTFUND,
    #[serde(rename = "PROPERTY_INVESTOR")]
    PROPERTYINVESTOR,
    #[serde(rename = "PROPERTY_MANAGEMENT")]
    PROPERTYMANAGEMENT,
    #[serde(rename = "PROPERTY_OTHER")]
    PROPERTYOTHER,
    #[serde(rename = "PROPERTY_OWNER")]
    PROPERTYOWNER,
    #[serde(rename = "PROPERTY_REDEVELOPMENT")]
    PROPERTYREDEVELOPMENT,
    #[serde(rename = "PUBLIC_SPEAKING")]
    PUBLICSPEAKING,
    #[serde(rename = "RAILWAYS")]
    RAILWAYS,
    #[serde(rename = "RECRUITMENT_AND_HIRING")]
    RECRUITMENTANDHIRING,
    #[serde(rename = "RELIGION")]
    RELIGION,
    #[serde(rename = "RESEARCH_AND_DEVELOPMENT")]
    RESEARCHANDDEVELOPMENT,
    #[serde(rename = "RESEARCH_AND_PUBLIC_POLICY")]
    RESEARCHANDPUBLICPOLICY,
    #[serde(rename = "RESIDENTS_ASSOCIATION")]
    RESIDENTSASSOCIATION,
    #[serde(rename = "RESTAURANT_OR_CAFE")]
    RESTAURANTORCAFE,
    #[serde(rename = "RETAIL")]
    RETAIL,
    #[serde(rename = "RETAIL_BARS_AND_RESTAURANTS_OTHER")]
    RETAILBARSANDRESTAURANTSOTHER,
    #[serde(rename = "RETAIL_INVESTMENT_BANK")]
    RETAILINVESTMENTBANK,
    #[serde(rename = "ROOFING")]
    ROOFING,
    #[serde(rename = "SALONS")]
    SALONS,
    #[serde(rename = "SCHOOLS_COLLEGES_AND_TRAINING")]
    SCHOOLSCOLLEGESANDTRAINING,
    #[serde(rename = "SCRAP_METAL")]
    SCRAPMETAL,
    #[serde(rename = "SECURITY")]
    SECURITY,
    #[serde(rename = "SHARE_TRADING")]
    SHARETRADING,
    #[serde(rename = "SITE_AND_BUILDING_MANAGEMENT")]
    SITEANDBUILDINGMANAGEMENT,
    #[serde(rename = "SOFTWARE_AND_IT")]
    SOFTWAREANDIT,
    #[serde(rename = "SPORTS_AND_FITNESS_VENUE")]
    SPORTSANDFITNESSVENUE,
    #[serde(rename = "SPORTS_CLUB")]
    SPORTSCLUB,
    #[serde(rename = "SPORTS_COACH")]
    SPORTSCOACH,
    #[serde(rename = "STORAGE")]
    STORAGE,
    #[serde(rename = "STREET_FOOD_OR_MARKET_STALL")]
    STREETFOODORMARKETSTALL,
    #[serde(rename = "STUDENT_RECRUITMENT")]
    STUDENTRECRUITMENT,
    #[serde(rename = "SUPPLIER_TO_AGRICULTURE_OR_INDUSTRY")]
    SUPPLIERTOAGRICULTUREORINDUSTRY,
    #[serde(rename = "TAKEAWAY")]
    TAKEAWAY,
    #[serde(rename = "TATTOO_PARLOUR")]
    TATTOOPARLOUR,
    #[serde(rename = "TAXI_OR_PRIVATE_HIRE_DRIVER")]
    TAXIORPRIVATEHIREDRIVER,
    #[serde(rename = "TAXI_OR_PRIVATE_HIRE_OPERATOR")]
    TAXIORPRIVATEHIREOPERATOR,
    #[serde(rename = "TOUR_GUIDE")]
    TOURGUIDE,
    #[serde(rename = "TRAIN_DRIVER")]
    TRAINDRIVER,
    #[serde(rename = "TRANSPORT_AND_VEHICLES_OTHER")]
    TRANSPORTANDVEHICLESOTHER,
    #[serde(rename = "TRAVEL_AGENT")]
    TRAVELAGENT,
    #[serde(rename = "TRUST_AND_COMPANY_SERVICE")]
    TRUSTANDCOMPANYSERVICE,
    #[serde(rename = "TV_AND_RADIO")]
    TVANDRADIO,
    #[serde(rename = "UK_GOVERNMENT")]
    UKGOVERNMENT,
    #[serde(rename = "UNEMPLOYED")]
    UNEMPLOYED,
    #[serde(rename = "USED_CAR_OR_VEHICLE_SALES")]
    USEDCARORVEHICLESALES,
    #[serde(rename = "VEHICLE_PARTS")]
    VEHICLEPARTS,
    #[serde(rename = "VEHICLE_RENTAL")]
    VEHICLERENTAL,
    #[serde(rename = "VEHICLE_REPAIR_AND_MAINTENANCE")]
    VEHICLEREPAIRANDMAINTENANCE,
    #[serde(rename = "VETERINARY")]
    VETERINARY,
    #[serde(rename = "WASTE_AND_RECYCLING")]
    WASTEANDRECYCLING,
    #[serde(rename = "WEBSITE_DEVELOPMENT")]
    WEBSITEDEVELOPMENT,
    #[serde(rename = "WHOLESALING")]
    WHOLESALING,
}

impl Default for EmploymentSector {
    fn default() -> EmploymentSector {
        Self::ACCOUNTANCYANDBOOKKEEPING
    }
}
/// Regulation status
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
)]
pub enum RegulationStatus {
    #[serde(rename = "REGULATED")]
    REGULATED,
    #[serde(rename = "NOT_REGULATED")]
    NOTREGULATED,
}

impl Default for RegulationStatus {
    fn default() -> RegulationStatus {
        Self::REGULATED
    }
}
