/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Enabling {
    #[serde(rename = "enabled")]
    pub enabled: bool,
}

impl Enabling {
    pub fn new(enabled: bool) -> Enabling {
        Enabling { enabled }
    }
}
