/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// ErrorDetail : Detail of the error

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ErrorDetail {
    /// The error message
    #[serde(
        rename = "message",
        skip_serializing_if = "Option::is_none"
    )]
    pub message: Option<String>,
}

impl ErrorDetail {
    /// Detail of the error
    pub fn new() -> ErrorDetail {
        ErrorDetail { message: None }
    }
}
