/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FeedItemAttachment {
    #[serde(
        rename = "feedItemUid",
        skip_serializing_if = "Option::is_none"
    )]
    pub feed_item_uid: Option<String>,
    #[serde(
        rename = "feedItemAttachmentUid",
        skip_serializing_if = "Option::is_none"
    )]
    pub feed_item_attachment_uid: Option<String>,
    #[serde(
        rename = "attachmentType",
        skip_serializing_if = "Option::is_none"
    )]
    pub attachment_type: Option<AttachmentType>,
    #[serde(
        rename = "feedItemAttachmentType",
        skip_serializing_if = "Option::is_none"
    )]
    pub feed_item_attachment_type: Option<FeedItemAttachmentType>,
}

impl FeedItemAttachment {
    pub fn new() -> FeedItemAttachment {
        FeedItemAttachment {
            feed_item_uid: None,
            feed_item_attachment_uid: None,
            attachment_type: None,
            feed_item_attachment_type: None,
        }
    }
}

///
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
)]
pub enum AttachmentType {
    #[serde(rename = "image, pdf")]
    ImagePdf,
}

impl Default for AttachmentType {
    fn default() -> AttachmentType {
        Self::ImagePdf
    }
}
///
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
)]
pub enum FeedItemAttachmentType {
    #[serde(rename = "IMAGE")]
    IMAGE,
    #[serde(rename = "PDF")]
    PDF,
    #[serde(rename = "IMAGE, PDF")]
    IMAGEPDF,
}

impl Default for FeedItemAttachmentType {
    fn default() -> FeedItemAttachmentType {
        Self::IMAGE
    }
}
