/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// FeedItems : Wrapper around multiple feed items

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FeedItems {
    #[serde(
        rename = "feedItems",
        skip_serializing_if = "Option::is_none"
    )]
    pub feed_items: Option<Vec<crate::models::FeedItem>>,
}

impl FeedItems {
    /// Wrapper around multiple feed items
    pub fn new() -> FeedItems {
        FeedItems { feed_items: None }
    }
}
