/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FeedItemAttachments {
    #[serde(
        rename = "feedItemAttachments",
        skip_serializing_if = "Option::is_none"
    )]
    pub feed_item_attachments:
        Option<Vec<crate::models::FeedItemAttachment>>,
}

impl FeedItemAttachments {
    pub fn new() -> FeedItemAttachments {
        FeedItemAttachments {
            feed_item_attachments: None,
        }
    }
}
