/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IdentityV2 {
    #[serde(
        rename = "accountHolderUid",
        skip_serializing_if = "Option::is_none"
    )]
    pub account_holder_uid: Option<String>,
    #[serde(
        rename = "expiresAt",
        skip_serializing_if = "Option::is_none"
    )]
    pub expires_at: Option<String>,
    #[serde(
        rename = "expiresInSeconds",
        skip_serializing_if = "Option::is_none"
    )]
    pub expires_in_seconds: Option<i64>,
    /// The scopes which this token has permission to use e.g. balance:read
    #[serde(
        rename = "scopes",
        skip_serializing_if = "Option::is_none"
    )]
    pub scopes: Option<Vec<String>>,
    #[serde(
        rename = "authenticated",
        skip_serializing_if = "Option::is_none"
    )]
    pub authenticated: Option<bool>,
    #[serde(
        rename = "applicationUserUid",
        skip_serializing_if = "Option::is_none"
    )]
    pub application_user_uid: Option<String>,
    #[serde(
        rename = "consentExpiresAt",
        skip_serializing_if = "Option::is_none"
    )]
    pub consent_expires_at: Option<String>,
    /// Deprecated, use accountHolderUid instead
    #[serde(
        rename = "customerUid",
        skip_serializing_if = "Option::is_none"
    )]
    pub customer_uid: Option<String>,
}

impl IdentityV2 {
    pub fn new() -> IdentityV2 {
        IdentityV2 {
            account_holder_uid: None,
            expires_at: None,
            expires_in_seconds: None,
            scopes: None,
            authenticated: None,
            application_user_uid: None,
            consent_expires_at: None,
            customer_uid: None,
        }
    }
}
