/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IncomeBandDisplays {
    #[serde(
        rename = "incomeBandDisplays",
        skip_serializing_if = "Option::is_none"
    )]
    pub income_band_displays:
        Option<Vec<crate::models::IncomeBandDisplay>>,
}

impl IncomeBandDisplays {
    pub fn new() -> IncomeBandDisplays {
        IncomeBandDisplays {
            income_band_displays: None,
        }
    }
}
