/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// IncomeDetails : Details of the account holder's income

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IncomeDetails {
    #[serde(rename = "annualIncome")]
    pub annual_income: Box<crate::models::CurrencyAndAmount>,
    /// Account holder's source of funds
    #[serde(rename = "sourceOfFunds")]
    pub source_of_funds: std::collections::HashSet<SourceOfFunds>,
}

impl IncomeDetails {
    /// Details of the account holder's income
    pub fn new(
        annual_income: crate::models::CurrencyAndAmount,
        source_of_funds: SourceOfFunds,
    ) -> IncomeDetails {
        IncomeDetails {
            annual_income: Box::new(annual_income),
            source_of_funds,
        }
    }
}

/// Account holder's source of funds
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
)]
pub enum SourceOfFunds {
    #[serde(rename = "BENEFITS")]
    BENEFITS,
    #[serde(rename = "FRIENDS_AND_FAMILY")]
    FRIENDSANDFAMILY,
    #[serde(rename = "INVESTMENT")]
    INVESTMENT,
    #[serde(rename = "LOANS")]
    LOANS,
    #[serde(rename = "MONTHLY_SALARY")]
    MONTHLYSALARY,
    #[serde(rename = "PENSION")]
    PENSION,
    #[serde(rename = "PROPERTY")]
    PROPERTY,
    #[serde(rename = "WEEKLY_WAGES")]
    WEEKLYWAGES,
}

impl Default for SourceOfFunds {
    fn default() -> SourceOfFunds {
        Self::BENEFITS
    }
}
