/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// IncomeAndEmploymentDetails : Request to declare income and, if required, employment info

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IncomeAndEmploymentDetails {
    #[serde(rename = "personIncomeDeclaration")]
    pub person_income_declaration:
        Box<crate::models::PersonIncomeDeclaration>,
    #[serde(rename = "employmentDeclaration")]
    pub employment_declaration:
        Box<crate::models::EmploymentDeclaration>,
}

impl IncomeAndEmploymentDetails {
    /// Request to declare income and, if required, employment info
    pub fn new(
        person_income_declaration: crate::models::PersonIncomeDeclaration,
        employment_declaration: crate::models::EmploymentDeclaration,
    ) -> IncomeAndEmploymentDetails {
        IncomeAndEmploymentDetails {
            person_income_declaration: Box::new(
                person_income_declaration,
            ),
            employment_declaration: Box::new(employment_declaration),
        }
    }
}
