/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// IncomeBandDisplay : Income band and display text

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IncomeBandDisplay {
    #[serde(
        rename = "incomeBand",
        skip_serializing_if = "Option::is_none"
    )]
    pub income_band: Option<IncomeBand>,
    #[serde(
        rename = "displayText",
        skip_serializing_if = "Option::is_none"
    )]
    pub display_text: Option<String>,
}

impl IncomeBandDisplay {
    /// Income band and display text
    pub fn new() -> IncomeBandDisplay {
        IncomeBandDisplay {
            income_band: None,
            display_text: None,
        }
    }
}

///
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
)]
pub enum IncomeBand {
    #[serde(rename = "BAND_0")]
    _0,
    #[serde(rename = "BAND_1")]
    _1,
    #[serde(rename = "BAND_2")]
    _2,
    #[serde(rename = "BAND_3")]
    _3,
    #[serde(rename = "BAND_4")]
    _4,
    #[serde(rename = "BAND_5")]
    _5,
    #[serde(rename = "BAND_6")]
    _6,
}

impl Default for IncomeBand {
    fn default() -> IncomeBand {
        Self::_0
    }
}
