/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// Individual : Information about an individual account holder

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Individual {
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(
        rename = "firstName",
        skip_serializing_if = "Option::is_none"
    )]
    pub first_name: Option<String>,
    #[serde(
        rename = "lastName",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_name: Option<String>,
    #[serde(
        rename = "dateOfBirth",
        skip_serializing_if = "Option::is_none"
    )]
    pub date_of_birth: Option<String>,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "phone", skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
}

impl Individual {
    /// Information about an individual account holder
    pub fn new() -> Individual {
        Individual {
            title: None,
            first_name: None,
            last_name: None,
            date_of_birth: None,
            email: None,
            phone: None,
        }
    }
}
