/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// InstructLocalPaymentResponse : Response after attempting to create a local payment

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InstructLocalPaymentResponse {
    /// The uid of the payment order created by the instruction. N.B. this will not be the uid of any payment which is created by the payment order
    #[serde(
        rename = "paymentOrderUid",
        skip_serializing_if = "Option::is_none"
    )]
    pub payment_order_uid: Option<String>,
}

impl InstructLocalPaymentResponse {
    /// Response after attempting to create a local payment
    pub fn new() -> InstructLocalPaymentResponse {
        InstructLocalPaymentResponse {
            payment_order_uid: None,
        }
    }
}
