/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// JointAccount : Information about a joint account

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct JointAccount {
    #[serde(
        rename = "accountHolderUid",
        skip_serializing_if = "Option::is_none"
    )]
    pub account_holder_uid: Option<String>,
    #[serde(
        rename = "personOne",
        skip_serializing_if = "Option::is_none"
    )]
    pub person_one: Option<Box<crate::models::Individual>>,
    #[serde(
        rename = "personTwo",
        skip_serializing_if = "Option::is_none"
    )]
    pub person_two: Option<Box<crate::models::Individual>>,
}

impl JointAccount {
    /// Information about a joint account
    pub fn new() -> JointAccount {
        JointAccount {
            account_holder_uid: None,
            person_one: None,
            person_two: None,
        }
    }
}
