/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// LastPayment : Last direct debit payment

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LastPayment {
    #[serde(
        rename = "lastDate",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_date: Option<String>,
    #[serde(
        rename = "lastAmount",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_amount: Option<Box<crate::models::CurrencyAndAmount>>,
}

impl LastPayment {
    /// Last direct debit payment
    pub fn new() -> LastPayment {
        LastPayment {
            last_date: None,
            last_amount: None,
        }
    }
}
