/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LocalTime {
    #[serde(rename = "hour", skip_serializing_if = "Option::is_none")]
    pub hour: Option<i32>,
    #[serde(
        rename = "minute",
        skip_serializing_if = "Option::is_none"
    )]
    pub minute: Option<i32>,
    #[serde(
        rename = "second",
        skip_serializing_if = "Option::is_none"
    )]
    pub second: Option<i32>,
    #[serde(rename = "nano", skip_serializing_if = "Option::is_none")]
    pub nano: Option<i32>,
}

impl LocalTime {
    pub fn new() -> LocalTime {
        LocalTime {
            hour: None,
            minute: None,
            second: None,
            nano: None,
        }
    }
}
