/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MastercardFeedItem {
    #[serde(
        rename = "merchantIdentifier",
        skip_serializing_if = "Option::is_none"
    )]
    pub merchant_identifier: Option<String>,
    #[serde(rename = "mcc", skip_serializing_if = "Option::is_none")]
    pub mcc: Option<i32>,
    #[serde(
        rename = "posTimestamp",
        skip_serializing_if = "Option::is_none"
    )]
    pub pos_timestamp: Option<Box<crate::models::LocalTime>>,
    #[serde(
        rename = "authorisationCode",
        skip_serializing_if = "Option::is_none"
    )]
    pub authorisation_code: Option<String>,
    #[serde(
        rename = "cardLast4",
        skip_serializing_if = "Option::is_none"
    )]
    pub card_last4: Option<String>,
}

impl MastercardFeedItem {
    pub fn new() -> MastercardFeedItem {
        MastercardFeedItem {
            merchant_identifier: None,
            mcc: None,
            pos_timestamp: None,
            authorisation_code: None,
            card_last4: None,
        }
    }
}
