/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// NameChangeDocumentUploadConfirmation : Request with metadata about an uploaded supporting document

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NameChangeDocumentUploadConfirmation {
    /// The type of supporting document that has been uploaded
    #[serde(rename = "nameChangeDocumentType")]
    pub name_change_document_type: NameChangeDocumentType,
    /// The filename of the uploaded document
    #[serde(rename = "filename")]
    pub filename: String,
}

impl NameChangeDocumentUploadConfirmation {
    /// Request with metadata about an uploaded supporting document
    pub fn new(
        name_change_document_type: NameChangeDocumentType,
        filename: String,
    ) -> NameChangeDocumentUploadConfirmation {
        NameChangeDocumentUploadConfirmation {
            name_change_document_type,
            filename,
        }
    }
}

/// The type of supporting document that has been uploaded
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
)]
pub enum NameChangeDocumentType {
    #[serde(rename = "MARRIAGE_CERTIFICATE")]
    MARRIAGECERTIFICATE,
    #[serde(rename = "DEED_POLL")]
    DEEDPOLL,
    #[serde(rename = "DIVORCE_CERTIFICATE")]
    DIVORCECERTIFICATE,
    #[serde(rename = "BIRTH_CERTIFICATE")]
    BIRTHCERTIFICATE,
}

impl Default for NameChangeDocumentType {
    fn default() -> NameChangeDocumentType {
        Self::MARRIAGECERTIFICATE
    }
}
