/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// OnboardingResponse : Response after attempting to onboard an account holder

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OnboardingResponse {
    /// The unique identifier of the account holder which has been created
    #[serde(
        rename = "accountHolderUid",
        skip_serializing_if = "Option::is_none"
    )]
    pub account_holder_uid: Option<String>,
    #[serde(
        rename = "accessToken",
        skip_serializing_if = "Option::is_none"
    )]
    pub access_token: Option<Box<crate::models::AccessToken>>,
}

impl OnboardingResponse {
    /// Response after attempting to onboard an account holder
    pub fn new() -> OnboardingResponse {
        OnboardingResponse {
            account_holder_uid: None,
            access_token: None,
        }
    }
}
