/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// OnboardingStatus : The onboarding status of an account holder

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OnboardingStatus {
    /// The current stage of onboarding
    #[serde(
        rename = "onboardingStage",
        skip_serializing_if = "Option::is_none"
    )]
    pub onboarding_stage: Option<OnboardingStage>,
    /// The time that onboarding was completed, only present if onboarding has in fact completed
    #[serde(
        rename = "onboardingCompletedAt",
        skip_serializing_if = "Option::is_none"
    )]
    pub onboarding_completed_at: Option<String>,
}

impl OnboardingStatus {
    /// The onboarding status of an account holder
    pub fn new() -> OnboardingStatus {
        OnboardingStatus {
            onboarding_stage: None,
            onboarding_completed_at: None,
        }
    }
}

/// The current stage of onboarding
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
)]
pub enum OnboardingStage {
    #[serde(rename = "ONBOARDING_REQUEST_SUBMITTED")]
    REQUESTSUBMITTED,
    #[serde(rename = "ONBOARDING_COMPLETE")]
    COMPLETE,
    #[serde(rename = "ONBOARDING_REJECTED")]
    REJECTED,
}

impl Default for OnboardingStage {
    fn default() -> OnboardingStage {
        Self::REQUESTSUBMITTED
    }
}
