/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// PayeeAccountCreationRequest : Request to create a payee account

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PayeeAccountCreationRequest {
    /// Account description
    #[serde(rename = "description")]
    pub description: String,
    /// Is this the default account for the owning payee
    #[serde(rename = "defaultAccount")]
    pub default_account: bool,
    /// The country code for the account (ISO 3166-1 alpha-2)
    #[serde(rename = "countryCode")]
    pub country_code: String,
    /// The account identifier
    #[serde(rename = "accountIdentifier")]
    pub account_identifier: String,
    /// The bank identifier
    #[serde(rename = "bankIdentifier")]
    pub bank_identifier: String,
    /// The bank identifier type
    #[serde(rename = "bankIdentifierType")]
    pub bank_identifier_type: BankIdentifierType,
    /// Secondary reference data (SRD), if applicable
    #[serde(
        rename = "secondaryIdentifier",
        skip_serializing_if = "Option::is_none"
    )]
    pub secondary_identifier: Option<String>,
}

impl PayeeAccountCreationRequest {
    /// Request to create a payee account
    pub fn new(
        description: String,
        default_account: bool,
        country_code: String,
        account_identifier: String,
        bank_identifier: String,
        bank_identifier_type: BankIdentifierType,
    ) -> PayeeAccountCreationRequest {
        PayeeAccountCreationRequest {
            description,
            default_account,
            country_code,
            account_identifier,
            bank_identifier,
            bank_identifier_type,
            secondary_identifier: None,
        }
    }
}

/// The bank identifier type
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
)]
pub enum BankIdentifierType {
    #[serde(rename = "SORT_CODE")]
    SORTCODE,
    #[serde(rename = "SWIFT")]
    SWIFT,
    #[serde(rename = "IBAN")]
    IBAN,
    #[serde(rename = "ABA")]
    ABA,
    #[serde(rename = "ABA_WIRE")]
    ABAWIRE,
    #[serde(rename = "ABA_ACH")]
    ABAACH,
    #[serde(rename = "BSB")]
    BSB,
}

impl Default for BankIdentifierType {
    fn default() -> BankIdentifierType {
        Self::SORTCODE
    }
}
