/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// PayeeAccountCreationResponse : Response after attempting to create a payee account

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PayeeAccountCreationResponse {
    /// The newly created payee unique identifier, only present on successful payee account creation
    #[serde(
        rename = "payeeAccountUid",
        skip_serializing_if = "Option::is_none"
    )]
    pub payee_account_uid: Option<String>,
    /// True if the method completed successfully
    #[serde(
        rename = "success",
        skip_serializing_if = "Option::is_none"
    )]
    pub success: Option<bool>,
    #[serde(
        rename = "errors",
        skip_serializing_if = "Option::is_none"
    )]
    pub errors: Option<Vec<crate::models::ErrorDetail>>,
}

impl PayeeAccountCreationResponse {
    /// Response after attempting to create a payee account
    pub fn new() -> PayeeAccountCreationResponse {
        PayeeAccountCreationResponse {
            payee_account_uid: None,
            success: None,
            errors: None,
        }
    }
}
