/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// Payee : A saved payee

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Payee {
    /// The uid of this payee
    #[serde(
        rename = "payeeUid",
        skip_serializing_if = "Option::is_none"
    )]
    pub payee_uid: Option<String>,
    /// Name
    #[serde(
        rename = "payeeName",
        skip_serializing_if = "Option::is_none"
    )]
    pub payee_name: Option<String>,
    /// Phone number
    #[serde(
        rename = "phoneNumber",
        skip_serializing_if = "Option::is_none"
    )]
    pub phone_number: Option<String>,
    /// INDIVIDUAL
    #[serde(
        rename = "payeeType",
        skip_serializing_if = "Option::is_none"
    )]
    pub payee_type: Option<PayeeType>,
    /// First name
    #[serde(
        rename = "firstName",
        skip_serializing_if = "Option::is_none"
    )]
    pub first_name: Option<String>,
    /// Middle name
    #[serde(
        rename = "middleName",
        skip_serializing_if = "Option::is_none"
    )]
    pub middle_name: Option<String>,
    /// Last name
    #[serde(
        rename = "lastName",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_name: Option<String>,
    /// Business name
    #[serde(
        rename = "businessName",
        skip_serializing_if = "Option::is_none"
    )]
    pub business_name: Option<String>,
    /// Date of birth
    #[serde(
        rename = "dateOfBirth",
        skip_serializing_if = "Option::is_none"
    )]
    pub date_of_birth: Option<String>,
    /// Accounts for this payee
    #[serde(
        rename = "accounts",
        skip_serializing_if = "Option::is_none"
    )]
    pub accounts: Option<Vec<crate::models::PayeeAccount>>,
}

impl Payee {
    /// A saved payee
    pub fn new() -> Payee {
        Payee {
            payee_uid: None,
            payee_name: None,
            phone_number: None,
            payee_type: None,
            first_name: None,
            middle_name: None,
            last_name: None,
            business_name: None,
            date_of_birth: None,
            accounts: None,
        }
    }
}

/// INDIVIDUAL
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
)]
pub enum PayeeType {
    #[serde(rename = "BUSINESS")]
    BUSINESS,
    #[serde(rename = "INDIVIDUAL")]
    INDIVIDUAL,
}

impl Default for PayeeType {
    fn default() -> PayeeType {
        Self::BUSINESS
    }
}
