/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// PayeeCreationResponse : Response after attempting to create a payee

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PayeeCreationResponse {
    /// The newly created payee unique identifier, only present on successful payee creation
    #[serde(
        rename = "payeeUid",
        skip_serializing_if = "Option::is_none"
    )]
    pub payee_uid: Option<String>,
    /// True if the method completed successfully
    #[serde(
        rename = "success",
        skip_serializing_if = "Option::is_none"
    )]
    pub success: Option<bool>,
    #[serde(
        rename = "errors",
        skip_serializing_if = "Option::is_none"
    )]
    pub errors: Option<Vec<crate::models::ErrorDetail>>,
}

impl PayeeCreationResponse {
    /// Response after attempting to create a payee
    pub fn new() -> PayeeCreationResponse {
        PayeeCreationResponse {
            payee_uid: None,
            success: None,
            errors: None,
        }
    }
}
