/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// PaymentOrderPaymentsResponse : List of payments associated with a payment order

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PaymentOrderPaymentsResponse {
    #[serde(rename = "payments")]
    pub payments: Vec<crate::models::PaymentOrderPayment>,
}

impl PaymentOrderPaymentsResponse {
    /// List of payments associated with a payment order
    pub fn new(
        payments: Vec<crate::models::PaymentOrderPayment>,
    ) -> PaymentOrderPaymentsResponse {
        PaymentOrderPaymentsResponse { payments }
    }
}
