/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// PaymentStatusDetails : Status details of a payment

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PaymentStatusDetails {
    #[serde(
        rename = "paymentStatus",
        skip_serializing_if = "Option::is_none"
    )]
    pub payment_status: Option<PaymentStatus>,
    #[serde(
        rename = "description",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Description>,
}

impl PaymentStatusDetails {
    /// Status details of a payment
    pub fn new() -> PaymentStatusDetails {
        PaymentStatusDetails {
            payment_status: None,
            description: None,
        }
    }
}

///
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
)]
pub enum PaymentStatus {
    #[serde(rename = "ACCEPTED")]
    ACCEPTED,
    #[serde(rename = "REJECTED")]
    REJECTED,
    #[serde(rename = "PENDING")]
    PENDING,
}

impl Default for PaymentStatus {
    fn default() -> PaymentStatus {
        Self::ACCEPTED
    }
}
///
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
)]
pub enum Description {
    #[serde(rename = "ACCEPTED")]
    ACCEPTED,
    #[serde(rename = "QUALIFIED_ACCEPT_WITHIN_TWO_HOURS")]
    QUALIFIEDACCEPTWITHINTWOHOURS,
    #[serde(rename = "QUALIFIED_ACCEPT_UNSPECIFIED_DAY")]
    QUALIFIEDACCEPTUNSPECIFIEDDAY,
    #[serde(rename = "QUALIFIED_ACCEPT_SAME_DAY")]
    QUALIFIEDACCEPTSAMEDAY,
    #[serde(rename = "QUALIFIED_ACCEPT_NEXT_CALENDAR_DAY")]
    QUALIFIEDACCEPTNEXTCALENDARDAY,
    #[serde(rename = "QUALIFIED_ACCEPT_NEXT_WORKING_DAY")]
    QUALIFIEDACCEPTNEXTWORKINGDAY,
    #[serde(rename = "QUALIFIED_ACCEPT_AFTER_NEXT_WORKING_DAY")]
    QUALIFIEDACCEPTAFTERNEXTWORKINGDAY,
    #[serde(rename = "DESTINATION_ACCOUNT_INVALID")]
    DESTINATIONACCOUNTINVALID,
    #[serde(rename = "DESTINATION_ACCOUNT_NAME_MISMATCH")]
    DESTINATIONACCOUNTNAMEMISMATCH,
    #[serde(rename = "REFERENCE_INFORMATION_INCORRECT")]
    REFERENCEINFORMATIONINCORRECT,
    #[serde(rename = "DESTINATION_ACCOUNT_UNAVAILABLE")]
    DESTINATIONACCOUNTUNAVAILABLE,
    #[serde(rename = "PENDING")]
    PENDING,
}

impl Default for Description {
    fn default() -> Description {
        Self::ACCEPTED
    }
}
