/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// PersonReverificationRequest : A request for person reverification

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PersonReverificationRequest {
    /// Whether the email has been verified
    #[serde(rename = "emailVerified")]
    pub email_verified: bool,
    /// External identifier
    #[serde(rename = "externalIdentifier")]
    pub external_identifier: String,
}

impl PersonReverificationRequest {
    /// A request for person reverification
    pub fn new(
        email_verified: bool,
        external_identifier: String,
    ) -> PersonReverificationRequest {
        PersonReverificationRequest {
            email_verified,
            external_identifier,
        }
    }
}
