/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// PersonTermsAcceptance : Required term details

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PersonTermsAcceptance {
    /// Name of the terms document
    #[serde(
        rename = "documentName",
        skip_serializing_if = "Option::is_none"
    )]
    pub document_name: Option<String>,
    /// Version of the terms document
    #[serde(
        rename = "version",
        skip_serializing_if = "Option::is_none"
    )]
    pub version: Option<i32>,
    /// Date the terms were first offered to the person being onboarded
    #[serde(
        rename = "firstOfferedDate",
        skip_serializing_if = "Option::is_none"
    )]
    pub first_offered_date: Option<String>,
    /// Date the terms were accepted by the person being onboarded
    #[serde(
        rename = "acceptanceDate",
        skip_serializing_if = "Option::is_none"
    )]
    pub acceptance_date: Option<String>,
    #[serde(
        rename = "accepted",
        skip_serializing_if = "Option::is_none"
    )]
    pub accepted: Option<bool>,
}

impl PersonTermsAcceptance {
    /// Required term details
    pub fn new() -> PersonTermsAcceptance {
        PersonTermsAcceptance {
            document_name: None,
            version: None,
            first_offered_date: None,
            acceptance_date: None,
            accepted: None,
        }
    }
}
