/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// PersonReverificationPhrase : Identity verification phrase for a customer

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PersonReverificationPhrase {
    /// The phrase UID
    #[serde(
        rename = "phraseUid",
        skip_serializing_if = "Option::is_none"
    )]
    pub phrase_uid: Option<String>,
    /// The phrase for identity verification
    #[serde(
        rename = "phrase",
        skip_serializing_if = "Option::is_none"
    )]
    pub phrase: Option<String>,
}

impl PersonReverificationPhrase {
    /// Identity verification phrase for a customer
    pub fn new() -> PersonReverificationPhrase {
        PersonReverificationPhrase {
            phrase_uid: None,
            phrase: None,
        }
    }
}
