/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// PersonTermsAcceptanceResponse : Response containing term names required

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PersonTermsAcceptanceResponse {
    /// List of required terms
    #[serde(
        rename = "personTermsAcceptances",
        skip_serializing_if = "Option::is_none"
    )]
    pub person_terms_acceptances:
        Option<Vec<crate::models::PersonTermsAcceptance>>,
}

impl PersonTermsAcceptanceResponse {
    /// Response containing term names required
    pub fn new() -> PersonTermsAcceptanceResponse {
        PersonTermsAcceptanceResponse {
            person_terms_acceptances: None,
        }
    }
}
