/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// PersonIncomeDeclaration : Declaration of person's income, its source, and a currency

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PersonIncomeDeclaration {
    /// Income band for this declaration
    #[serde(rename = "incomeBand")]
    pub income_band: IncomeBand,
    /// Currency code
    #[serde(rename = "currencyCode")]
    pub currency_code: String,
    /// Source of funds
    #[serde(rename = "sourcesOfFunds")]
    pub sources_of_funds: std::collections::HashSet<SourcesOfFunds>,
}

impl PersonIncomeDeclaration {
    /// Declaration of person's income, its source, and a currency
    pub fn new(
        income_band: IncomeBand,
        currency_code: String,
        sources_of_funds: SourcesOfFunds,
    ) -> PersonIncomeDeclaration {
        PersonIncomeDeclaration {
            income_band,
            currency_code,
            sources_of_funds,
        }
    }
}

/// Income band for this declaration
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
)]
pub enum IncomeBand {
    #[serde(rename = "BAND_0")]
    _0,
    #[serde(rename = "BAND_1")]
    _1,
    #[serde(rename = "BAND_2")]
    _2,
    #[serde(rename = "BAND_3")]
    _3,
    #[serde(rename = "BAND_4")]
    _4,
    #[serde(rename = "BAND_5")]
    _5,
    #[serde(rename = "BAND_6")]
    _6,
}

impl Default for IncomeBand {
    fn default() -> IncomeBand {
        Self::_0
    }
}
/// Source of funds
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
)]
pub enum SourcesOfFunds {
    #[serde(rename = "BENEFITS")]
    BENEFITS,
    #[serde(rename = "FRIENDS_AND_FAMILY")]
    FRIENDSANDFAMILY,
    #[serde(rename = "INVESTMENT")]
    INVESTMENT,
    #[serde(rename = "LOANS")]
    LOANS,
    #[serde(rename = "MONTHLY_SALARY")]
    MONTHLYSALARY,
    #[serde(rename = "PENSION")]
    PENSION,
    #[serde(rename = "PROPERTY")]
    PROPERTY,
    #[serde(rename = "WEEKLY_WAGES")]
    WEEKLYWAGES,
    #[serde(rename = "SELF_EMPLOYMENT_INCOME")]
    SELFEMPLOYMENTINCOME,
    #[serde(rename = "DIVIDENDS")]
    DIVIDENDS,
}

impl Default for SourcesOfFunds {
    fn default() -> SourcesOfFunds {
        Self::BENEFITS
    }
}
