/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// PresignedUploadRequest : Request to generate an upload URL for identity information

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PresignedUploadRequest {
    #[serde(rename = "mimeType")]
    pub mime_type: Box<crate::models::PresignedUploadRequestMimeType>,
    /// A MD5 checksum of the content to be uploaded
    #[serde(rename = "md5Checksum")]
    pub md5_checksum: String,
}

impl PresignedUploadRequest {
    /// Request to generate an upload URL for identity information
    pub fn new(
        mime_type: crate::models::PresignedUploadRequestMimeType,
        md5_checksum: String,
    ) -> PresignedUploadRequest {
        PresignedUploadRequest {
            mime_type: Box::new(mime_type),
            md5_checksum,
        }
    }
}
