/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// PresignedUploadUrl : Identity document upload URL response

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PresignedUploadUrl {
    /// Presigned media document upload URL
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// Identity Document Upload UID
    #[serde(
        rename = "identityUploadUid",
        skip_serializing_if = "Option::is_none"
    )]
    pub identity_upload_uid: Option<String>,
}

impl PresignedUploadUrl {
    /// Identity document upload URL response
    pub fn new() -> PresignedUploadUrl {
        PresignedUploadUrl {
            url: None,
            identity_upload_uid: None,
        }
    }
}
