/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// PresignedUrlRequest : Request to generate an upload URL for submitting documentation

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PresignedUrlRequest {
    #[serde(
        rename = "contentType",
        skip_serializing_if = "Option::is_none"
    )]
    pub content_type:
        Option<Box<crate::models::ConfirmUploadRequestContentType>>,
    #[serde(
        rename = "contentMd5",
        skip_serializing_if = "Option::is_none"
    )]
    pub content_md5: Option<String>,
    #[serde(rename = "mimeType")]
    pub mime_type: Box<crate::models::PresignedUrlRequestMimeType>,
    /// A MD5 checksum of the content to be uploaded
    #[serde(rename = "md5Checksum")]
    pub md5_checksum: String,
}

impl PresignedUrlRequest {
    /// Request to generate an upload URL for submitting documentation
    pub fn new(
        mime_type: crate::models::PresignedUrlRequestMimeType,
        md5_checksum: String,
    ) -> PresignedUrlRequest {
        PresignedUrlRequest {
            content_type: None,
            content_md5: None,
            mime_type: Box::new(mime_type),
            md5_checksum,
        }
    }
}
