/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// ProofOfAddressActions : Proof of address status

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProofOfAddressActions {
    /// Proof of address onboarding status
    #[serde(
        rename = "status",
        skip_serializing_if = "Option::is_none"
    )]
    pub status: Option<Status>,
    /// Dynamically generated list of acceptable proof of address documents for the user
    #[serde(
        rename = "acceptableDocumentTypes",
        skip_serializing_if = "Option::is_none"
    )]
    pub acceptable_document_types: Option<Vec<AcceptableDocumentTypes>>,
    /// Reasons the document was rejected
    #[serde(
        rename = "rejectionReasons",
        skip_serializing_if = "Option::is_none"
    )]
    pub rejection_reasons: Option<Vec<RejectionReasons>>,
}

impl ProofOfAddressActions {
    /// Proof of address status
    pub fn new() -> ProofOfAddressActions {
        ProofOfAddressActions {
            status: None,
            acceptable_document_types: None,
            rejection_reasons: None,
        }
    }
}

/// Proof of address onboarding status
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
)]
pub enum Status {
    #[serde(rename = "AWAITING_UPLOAD")]
    AWAITINGUPLOAD,
    #[serde(rename = "READY_FOR_REVIEW")]
    READYFORREVIEW,
    #[serde(rename = "NOT_REQUIRED")]
    NOTREQUIRED,
}

impl Default for Status {
    fn default() -> Status {
        Self::AWAITINGUPLOAD
    }
}
/// Dynamically generated list of acceptable proof of address documents for the user
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
)]
pub enum AcceptableDocumentTypes {
    #[serde(rename = "FULL_DRIVING_LICENSE")]
    FULLDRIVINGLICENSE,
    #[serde(rename = "PROVISIONAL_DRIVING_LICENSE")]
    PROVISIONALDRIVINGLICENSE,
    #[serde(rename = "BANK_STATEMENT")]
    BANKSTATEMENT,
    #[serde(rename = "FINANCIAL_STATEMENT")]
    FINANCIALSTATEMENT,
    #[serde(rename = "UTILITY_BILL")]
    UTILITYBILL,
    #[serde(rename = "GOVERNMENT_LETTER")]
    GOVERNMENTLETTER,
    #[serde(rename = "COUNCIL_TAX")]
    COUNCILTAX,
    #[serde(rename = "HOUSING_LETTER")]
    HOUSINGLETTER,
    #[serde(rename = "UNIVERSITY_LETTER")]
    UNIVERSITYLETTER,
    #[serde(rename = "NI_LETTER")]
    NILETTER,
}

impl Default for AcceptableDocumentTypes {
    fn default() -> AcceptableDocumentTypes {
        Self::FULLDRIVINGLICENSE
    }
}
/// Reasons the document was rejected
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
)]
pub enum RejectionReasons {
    #[serde(rename = "NOT_ACCEPTABLE_DOC_TYPE")]
    NOTACCEPTABLEDOCTYPE,
    #[serde(rename = "DOC_OUT_OF_DATE")]
    DOCOUTOFDATE,
    #[serde(rename = "SOME_INFORMATION_ILLEGIBLE")]
    SOMEINFORMATIONILLEGIBLE,
    #[serde(rename = "PHOTO_BLURRY")]
    PHOTOBLURRY,
    #[serde(rename = "PHOTO_TOO_DARK")]
    PHOTOTOODARK,
    #[serde(rename = "PHOTO_CROPPED")]
    PHOTOCROPPED,
    #[serde(rename = "PHOTO_PARTIALLY_COVERED")]
    PHOTOPARTIALLYCOVERED,
    #[serde(rename = "PHOTO_REFLECTION")]
    PHOTOREFLECTION,
    #[serde(rename = "PHOTO_NO_FACE")]
    PHOTONOFACE,
    #[serde(rename = "DOB_NOT_VISIBLE")]
    DOBNOTVISIBLE,
    #[serde(rename = "DOCUMENT_DAMAGED")]
    DOCUMENTDAMAGED,
    #[serde(rename = "CANNOT_VALIDATE")]
    CANNOTVALIDATE,
    #[serde(rename = "MUST_BE_ORIGINAL")]
    MUSTBEORIGINAL,
    #[serde(rename = "ADDRESS_MISMATCH")]
    ADDRESSMISMATCH,
    #[serde(rename = "PARTIAL_OR_MISSING_ADDRESS")]
    PARTIALORMISSINGADDRESS,
    #[serde(rename = "NAME_MISMATCH")]
    NAMEMISMATCH,
    #[serde(rename = "NEEDS_FULL_DOC")]
    NEEDSFULLDOC,
    #[serde(rename = "NEEDS_RESIDENCE_PERMIT")]
    NEEDSRESIDENCEPERMIT,
    #[serde(rename = "NEEDS_PASSPORT")]
    NEEDSPASSPORT,
    #[serde(rename = "UNKNOWN")]
    UNKNOWN,
}

impl Default for RejectionReasons {
    fn default() -> RejectionReasons {
        Self::NOTACCEPTABLEDOCTYPE
    }
}
