/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// ReceiptNote : Note associated with a receipt

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ReceiptNote {
    #[serde(
        rename = "noteUid",
        skip_serializing_if = "Option::is_none"
    )]
    pub note_uid: Option<String>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl ReceiptNote {
    /// Note associated with a receipt
    pub fn new(description: String) -> ReceiptNote {
        ReceiptNote {
            note_uid: None,
            title: None,
            description,
            url: None,
        }
    }
}
