/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// ReceiptMerchant : Receipt Merchant Information

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ReceiptMerchant {
    #[serde(
        rename = "receiptMerchantUid",
        skip_serializing_if = "Option::is_none"
    )]
    pub receipt_merchant_uid: Option<String>,
    #[serde(
        rename = "identifier",
        skip_serializing_if = "Option::is_none"
    )]
    pub identifier: Option<String>,
    #[serde(
        rename = "address",
        skip_serializing_if = "Option::is_none"
    )]
    pub address: Option<String>,
    #[serde(
        rename = "emailAddress",
        skip_serializing_if = "Option::is_none"
    )]
    pub email_address: Option<String>,
    #[serde(
        rename = "logoUrl",
        skip_serializing_if = "Option::is_none"
    )]
    pub logo_url: Option<String>,
    #[serde(
        rename = "orderCollectionNumber",
        skip_serializing_if = "Option::is_none"
    )]
    pub order_collection_number: Option<String>,
    #[serde(
        rename = "taxNumber",
        skip_serializing_if = "Option::is_none"
    )]
    pub tax_number: Option<String>,
}

impl ReceiptMerchant {
    /// Receipt Merchant Information
    pub fn new() -> ReceiptMerchant {
        ReceiptMerchant {
            receipt_merchant_uid: None,
            identifier: None,
            address: None,
            email_address: None,
            logo_url: None,
            order_collection_number: None,
            tax_number: None,
        }
    }
}
