/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ReceiptPaymentMethod {
    #[serde(
        rename = "paymentMethodUid",
        skip_serializing_if = "Option::is_none"
    )]
    pub payment_method_uid: Option<String>,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "amount")]
    pub amount: f32,
}

impl ReceiptPaymentMethod {
    pub fn new(
        description: String,
        amount: f32,
    ) -> ReceiptPaymentMethod {
        ReceiptPaymentMethod {
            payment_method_uid: None,
            description,
            amount,
        }
    }
}
