/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// ReceiptCreationResponse : Response after creating or updating a receipt

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ReceiptCreationResponse {
    /// The UUID of the created receipt. This UUID could be used for updating the receipt at a later point.
    #[serde(
        rename = "receiptUid",
        skip_serializing_if = "Option::is_none"
    )]
    pub receipt_uid: Option<String>,
}

impl ReceiptCreationResponse {
    /// Response after creating or updating a receipt
    pub fn new() -> ReceiptCreationResponse {
        ReceiptCreationResponse { receipt_uid: None }
    }
}
