/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// RecurringCardPayments : List of recurring card payments

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RecurringCardPayments {
    /// List of recurring card payments
    #[serde(
        rename = "recurringPayments",
        skip_serializing_if = "Option::is_none"
    )]
    pub recurring_payments:
        Option<Vec<crate::models::RecurringCardPayment>>,
}

impl RecurringCardPayments {
    /// List of recurring card payments
    pub fn new() -> RecurringCardPayments {
        RecurringCardPayments {
            recurring_payments: None,
        }
    }
}
