/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RoundUpGoalDetails {
    #[serde(rename = "primaryCategoryUid")]
    pub primary_category_uid: String,
    #[serde(rename = "roundUpGoalUid")]
    pub round_up_goal_uid: String,
    #[serde(rename = "roundUpMultiplier")]
    pub round_up_multiplier: f32,
    #[serde(rename = "activatedAt")]
    pub activated_at: String,
    #[serde(rename = "activatedBy")]
    pub activated_by: String,
}

impl RoundUpGoalDetails {
    pub fn new(
        primary_category_uid: String,
        round_up_goal_uid: String,
        round_up_multiplier: f32,
        activated_at: String,
        activated_by: String,
    ) -> RoundUpGoalDetails {
        RoundUpGoalDetails {
            primary_category_uid,
            round_up_goal_uid,
            round_up_multiplier,
            activated_at,
            activated_by,
        }
    }
}
