/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RoundUpGoalPayload {
    /// UID of the account category to send round-ups to
    #[serde(rename = "roundUpGoalUid")]
    pub round_up_goal_uid: String,
    /// How much to multiply the rounded-up amount by before transfer. Must be an integer between 1 and 10 (inclusive)
    #[serde(rename = "roundUpMultiplier")]
    pub round_up_multiplier: i32,
}

impl RoundUpGoalPayload {
    pub fn new(
        round_up_goal_uid: String,
        round_up_multiplier: i32,
    ) -> RoundUpGoalPayload {
        RoundUpGoalPayload {
            round_up_goal_uid,
            round_up_multiplier,
        }
    }
}
