/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// SavingsGoalTransferResponseV2 : Response after attempting to make an immediate or recurring transfer into/out of a savings goal.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SavingsGoalTransferResponseV2 {
    /// Unique identifier for the transfer
    #[serde(rename = "transferUid")]
    pub transfer_uid: String,
    /// True if the method completed successfully
    #[serde(
        rename = "success",
        skip_serializing_if = "Option::is_none"
    )]
    pub success: Option<bool>,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<Vec<crate::models::ErrorDetail>>,
    /// List of errors if the method request failed
    #[serde(
        rename = "errors",
        skip_serializing_if = "Option::is_none"
    )]
    pub errors: Option<Vec<crate::models::ErrorDetail>>,
}

impl SavingsGoalTransferResponseV2 {
    /// Response after attempting to make an immediate or recurring transfer into/out of a savings goal.
    pub fn new(transfer_uid: String) -> SavingsGoalTransferResponseV2 {
        SavingsGoalTransferResponseV2 {
            transfer_uid,
            success: None,
            error: None,
            errors: None,
        }
    }
}
