/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// SavingsGoalV2 : A goal defined by an account holder to hold savings

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SavingsGoalV2 {
    /// Unique identifier of the savings goal
    #[serde(
        rename = "savingsGoalUid",
        skip_serializing_if = "Option::is_none"
    )]
    pub savings_goal_uid: Option<String>,
    /// Name of the savings goal
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(
        rename = "target",
        skip_serializing_if = "Option::is_none"
    )]
    pub target: Option<Box<crate::models::CurrencyAndAmount>>,
    #[serde(
        rename = "totalSaved",
        skip_serializing_if = "Option::is_none"
    )]
    pub total_saved: Option<Box<crate::models::CurrencyAndAmount>>,
    /// Percentage of target currently deposited in the savings goal
    #[serde(
        rename = "savedPercentage",
        skip_serializing_if = "Option::is_none"
    )]
    pub saved_percentage: Option<i32>,
}

impl SavingsGoalV2 {
    /// A goal defined by an account holder to hold savings
    pub fn new() -> SavingsGoalV2 {
        SavingsGoalV2 {
            savings_goal_uid: None,
            name: None,
            target: None,
            total_saved: None,
            saved_percentage: None,
        }
    }
}
