/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// SavingsGoalRequestV2 : Request to create a new savings goal

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SavingsGoalRequestV2 {
    /// Name of the savings goal
    #[serde(rename = "name")]
    pub name: String,
    /// ISO-4217 3 character currency code of the savings goal
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(
        rename = "target",
        skip_serializing_if = "Option::is_none"
    )]
    pub target: Option<Box<crate::models::CurrencyAndAmount>>,
    /// A text (base 64) encoded picture to associate with the savings goal
    #[serde(
        rename = "base64EncodedPhoto",
        skip_serializing_if = "Option::is_none"
    )]
    pub base64_encoded_photo: Option<String>,
}

impl SavingsGoalRequestV2 {
    /// Request to create a new savings goal
    pub fn new(name: String, currency: String) -> SavingsGoalRequestV2 {
        SavingsGoalRequestV2 {
            name,
            currency,
            target: None,
            base64_encoded_photo: None,
        }
    }
}
