/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// SavingsGoalsV2 : A list containing all savings goals for account holder

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SavingsGoalsV2 {
    #[serde(rename = "savingsGoalList")]
    pub savings_goal_list: Vec<crate::models::SavingsGoalV2>,
}

impl SavingsGoalsV2 {
    /// A list containing all savings goals for account holder
    pub fn new(
        savings_goal_list: Vec<crate::models::SavingsGoalV2>,
    ) -> SavingsGoalsV2 {
        SavingsGoalsV2 { savings_goal_list }
    }
}
