/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// ScheduledPayment : Response object for scheduled payments queries

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ScheduledPayment {
    /// Unique identifier for account holder
    #[serde(
        rename = "accountHolderUid",
        skip_serializing_if = "Option::is_none"
    )]
    pub account_holder_uid: Option<String>,
    /// Unique identifier of the scheduled payment order
    #[serde(
        rename = "paymentOrderUid",
        skip_serializing_if = "Option::is_none"
    )]
    pub payment_order_uid: Option<String>,
    /// Unique identifier of the category from which the payment will be taken
    #[serde(
        rename = "categoryUid",
        skip_serializing_if = "Option::is_none"
    )]
    pub category_uid: Option<String>,
    #[serde(
        rename = "nextPaymentAmount",
        skip_serializing_if = "Option::is_none"
    )]
    pub next_payment_amount:
        Option<Box<crate::models::CurrencyAndAmount>>,
    /// Payment order reference
    #[serde(
        rename = "reference",
        skip_serializing_if = "Option::is_none"
    )]
    pub reference: Option<String>,
    /// Unique identifier of the payee
    #[serde(
        rename = "payeeUid",
        skip_serializing_if = "Option::is_none"
    )]
    pub payee_uid: Option<String>,
    /// Unique identifier of the payee account
    #[serde(
        rename = "payeeAccountUid",
        skip_serializing_if = "Option::is_none"
    )]
    pub payee_account_uid: Option<String>,
    /// Recipient name
    #[serde(
        rename = "recipientName",
        skip_serializing_if = "Option::is_none"
    )]
    pub recipient_name: Option<String>,
    #[serde(
        rename = "recurrenceRule",
        skip_serializing_if = "Option::is_none"
    )]
    pub recurrence_rule: Option<Box<crate::models::RecurrenceRule>>,
    /// Date when the payment order has been created
    #[serde(
        rename = "startDate",
        skip_serializing_if = "Option::is_none"
    )]
    pub start_date: Option<String>,
    /// Date of the next payment order
    #[serde(
        rename = "nextDate",
        skip_serializing_if = "Option::is_none"
    )]
    pub next_date: Option<String>,
    /// Date when payment order ends
    #[serde(
        rename = "endDate",
        skip_serializing_if = "Option::is_none"
    )]
    pub end_date: Option<String>,
    /// Payment type
    #[serde(
        rename = "paymentType",
        skip_serializing_if = "Option::is_none"
    )]
    pub payment_type: Option<PaymentType>,
    /// The category of a transaction
    #[serde(
        rename = "spendingCategory",
        skip_serializing_if = "Option::is_none"
    )]
    pub spending_category: Option<SpendingCategory>,
}

impl ScheduledPayment {
    /// Response object for scheduled payments queries
    pub fn new() -> ScheduledPayment {
        ScheduledPayment {
            account_holder_uid: None,
            payment_order_uid: None,
            category_uid: None,
            next_payment_amount: None,
            reference: None,
            payee_uid: None,
            payee_account_uid: None,
            recipient_name: None,
            recurrence_rule: None,
            start_date: None,
            next_date: None,
            end_date: None,
            payment_type: None,
            spending_category: None,
        }
    }
}

/// Payment type
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
)]
pub enum PaymentType {
    #[serde(rename = "DIRECT_DEBIT")]
    DIRECTDEBIT,
    #[serde(rename = "STANDING_ORDER")]
    STANDINGORDER,
    #[serde(rename = "INTERNAL_TRANSFER")]
    INTERNALTRANSFER,
}

impl Default for PaymentType {
    fn default() -> PaymentType {
        Self::DIRECTDEBIT
    }
}
/// The category of a transaction
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
)]
pub enum SpendingCategory {
    #[serde(rename = "BIKE")]
    BIKE,
    #[serde(rename = "BILLS_AND_SERVICES")]
    BILLSANDSERVICES,
    #[serde(rename = "BUCKET_LIST")]
    BUCKETLIST,
    #[serde(rename = "CAR")]
    CAR,
    #[serde(rename = "CASH")]
    CASH,
    #[serde(rename = "CELEBRATION")]
    CELEBRATION,
    #[serde(rename = "CHARITY")]
    CHARITY,
    #[serde(rename = "CHILDREN")]
    CHILDREN,
    #[serde(rename = "COFFEE")]
    COFFEE,
    #[serde(rename = "DEBT_REPAYMENT")]
    DEBTREPAYMENT,
    #[serde(rename = "DIY")]
    DIY,
    #[serde(rename = "DRINKS")]
    DRINKS,
    #[serde(rename = "EATING_OUT")]
    EATINGOUT,
    #[serde(rename = "EDUCATION")]
    EDUCATION,
    #[serde(rename = "EMERGENCY")]
    EMERGENCY,
    #[serde(rename = "ENTERTAINMENT")]
    ENTERTAINMENT,
    #[serde(rename = "ESSENTIAL_SPEND")]
    ESSENTIALSPEND,
    #[serde(rename = "EXPENSES")]
    EXPENSES,
    #[serde(rename = "FAMILY")]
    FAMILY,
    #[serde(rename = "FITNESS")]
    FITNESS,
    #[serde(rename = "FUEL")]
    FUEL,
    #[serde(rename = "GAMBLING")]
    GAMBLING,
    #[serde(rename = "GAMING")]
    GAMING,
    #[serde(rename = "GARDEN")]
    GARDEN,
    #[serde(rename = "GENERAL")]
    GENERAL,
    #[serde(rename = "GIFTS")]
    GIFTS,
    #[serde(rename = "GROCERIES")]
    GROCERIES,
    #[serde(rename = "HOBBY")]
    HOBBY,
    #[serde(rename = "HOLIDAYS")]
    HOLIDAYS,
    #[serde(rename = "HOME")]
    HOME,
    #[serde(rename = "IMPULSE_BUY")]
    IMPULSEBUY,
    #[serde(rename = "INCOME")]
    INCOME,
    #[serde(rename = "INSURANCE")]
    INSURANCE,
    #[serde(rename = "INVESTMENTS")]
    INVESTMENTS,
    #[serde(rename = "LIFESTYLE")]
    LIFESTYLE,
    #[serde(rename = "MAINTENANCE_AND_REPAIRS")]
    MAINTENANCEANDREPAIRS,
    #[serde(rename = "MEDICAL")]
    MEDICAL,
    #[serde(rename = "MORTGAGE")]
    MORTGAGE,
    #[serde(rename = "NON_ESSENTIAL_SPEND")]
    NONESSENTIALSPEND,
    #[serde(rename = "PAYMENTS")]
    PAYMENTS,
    #[serde(rename = "PERSONAL_TRANSFERS")]
    PERSONALTRANSFERS,
    #[serde(rename = "PETS")]
    PETS,
    #[serde(rename = "PROJECTS")]
    PROJECTS,
    #[serde(rename = "RELATIONSHIPS")]
    RELATIONSHIPS,
    #[serde(rename = "RENT")]
    RENT,
    #[serde(rename = "SAVING")]
    SAVING,
    #[serde(rename = "SHOPPING")]
    SHOPPING,
    #[serde(rename = "SUBSCRIPTIONS")]
    SUBSCRIPTIONS,
    #[serde(rename = "TAKEAWAY")]
    TAKEAWAY,
    #[serde(rename = "TAXI")]
    TAXI,
    #[serde(rename = "TRANSPORT")]
    TRANSPORT,
    #[serde(rename = "TREATS")]
    TREATS,
    #[serde(rename = "WEDDING")]
    WEDDING,
    #[serde(rename = "WELLBEING")]
    WELLBEING,
    #[serde(rename = "NONE")]
    NONE,
    #[serde(rename = "REVENUE")]
    REVENUE,
    #[serde(rename = "OTHER_INCOME")]
    OTHERINCOME,
    #[serde(rename = "CLIENT_REFUNDS")]
    CLIENTREFUNDS,
    #[serde(rename = "INVENTORY")]
    INVENTORY,
    #[serde(rename = "STAFF")]
    STAFF,
    #[serde(rename = "TRAVEL")]
    TRAVEL,
    #[serde(rename = "WORKPLACE")]
    WORKPLACE,
    #[serde(rename = "REPAIRS_AND_MAINTENANCE")]
    REPAIRSANDMAINTENANCE,
    #[serde(rename = "ADMIN")]
    ADMIN,
    #[serde(rename = "MARKETING")]
    MARKETING,
    #[serde(rename = "BUSINESS_ENTERTAINMENT")]
    BUSINESSENTERTAINMENT,
    #[serde(rename = "INTEREST_PAYMENTS")]
    INTERESTPAYMENTS,
    #[serde(rename = "BANK_CHARGES")]
    BANKCHARGES,
    #[serde(rename = "OTHER")]
    OTHER,
    #[serde(rename = "FOOD_AND_DRINK")]
    FOODANDDRINK,
    #[serde(rename = "EQUIPMENT")]
    EQUIPMENT,
    #[serde(rename = "PROFESSIONAL_SERVICES")]
    PROFESSIONALSERVICES,
    #[serde(rename = "PHONE_AND_INTERNET")]
    PHONEANDINTERNET,
    #[serde(rename = "VEHICLES")]
    VEHICLES,
    #[serde(rename = "DIRECTORS_WAGES")]
    DIRECTORSWAGES,
    #[serde(rename = "VAT")]
    VAT,
    #[serde(rename = "CORPORATION_TAX")]
    CORPORATIONTAX,
    #[serde(rename = "SELF_ASSESSMENT_TAX")]
    SELFASSESSMENTTAX,
    #[serde(rename = "INVESTMENT_CAPITAL")]
    INVESTMENTCAPITAL,
    #[serde(rename = "TRANSFERS")]
    TRANSFERS,
    #[serde(rename = "LOAN_PRINCIPAL")]
    LOANPRINCIPAL,
    #[serde(rename = "PERSONAL")]
    PERSONAL,
    #[serde(rename = "DIVIDENDS")]
    DIVIDENDS,
}

impl Default for SpendingCategory {
    fn default() -> SpendingCategory {
        Self::BIKE
    }
}
