/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ScheduledPaymentResponse {
    /// List of scheduled payments for a payee account
    #[serde(
        rename = "scheduledPayments",
        skip_serializing_if = "Option::is_none"
    )]
    pub scheduled_payments:
        Option<Vec<crate::models::ScheduledPayment>>,
}

impl ScheduledPaymentResponse {
    pub fn new() -> ScheduledPaymentResponse {
        ScheduledPaymentResponse {
            scheduled_payments: None,
        }
    }
}
