/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// ScheduledSavingsPaymentRequestV2 : Request to create scheduled payment into a savings goal

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ScheduledSavingsPaymentRequestV2 {
    #[serde(rename = "recurrenceRule")]
    pub recurrence_rule: Box<crate::models::RecurrenceRuleV2>,
    #[serde(rename = "amount")]
    pub amount: Box<crate::models::CurrencyAndAmount>,
    /// If the payment is a top up or not
    #[serde(rename = "topUp", skip_serializing_if = "Option::is_none")]
    pub top_up: Option<bool>,
}

impl ScheduledSavingsPaymentRequestV2 {
    /// Request to create scheduled payment into a savings goal
    pub fn new(
        recurrence_rule: crate::models::RecurrenceRuleV2,
        amount: crate::models::CurrencyAndAmount,
    ) -> ScheduledSavingsPaymentRequestV2 {
        ScheduledSavingsPaymentRequestV2 {
            recurrence_rule: Box::new(recurrence_rule),
            amount: Box::new(amount),
            top_up: None,
        }
    }
}
