/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SettleUpProfile {
    /// Status
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(
        rename = "starlingPayLink",
        skip_serializing_if = "Option::is_none"
    )]
    pub starling_pay_link: Option<String>,
    /// Settle Up link
    #[serde(rename = "settleUpLink")]
    pub settle_up_link: String,
}

impl SettleUpProfile {
    pub fn new(
        status: Status,
        settle_up_link: String,
    ) -> SettleUpProfile {
        SettleUpProfile {
            status,
            starling_pay_link: None,
            settle_up_link,
        }
    }
}

/// Status
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
)]
pub enum Status {
    #[serde(rename = "ACTIVE")]
    ACTIVE,
    #[serde(rename = "INACTIVE")]
    INACTIVE,
    #[serde(rename = "CLOSED")]
    CLOSED,
}

impl Default for Status {
    fn default() -> Status {
        Self::ACTIVE
    }
}
