/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// SoleTrader : Response object contain sole trader business details

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SoleTrader {
    /// Trading as name
    #[serde(
        rename = "tradingAsName",
        skip_serializing_if = "Option::is_none"
    )]
    pub trading_as_name: Option<String>,
    /// Business category
    #[serde(
        rename = "businessCategory",
        skip_serializing_if = "Option::is_none"
    )]
    pub business_category: Option<BusinessCategory>,
    /// Business subcategory
    #[serde(
        rename = "businessSubCategory",
        skip_serializing_if = "Option::is_none"
    )]
    pub business_sub_category: Option<BusinessSubCategory>,
}

impl SoleTrader {
    /// Response object contain sole trader business details
    pub fn new() -> SoleTrader {
        SoleTrader {
            trading_as_name: None,
            business_category: None,
            business_sub_category: None,
        }
    }
}

/// Business category
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
)]
pub enum BusinessCategory {
    #[serde(rename = "NOT_PROVIDED")]
    NOTPROVIDED,
    #[serde(rename = "ARTS_CRAFTS_AND_COLLECTIBLES")]
    ARTSCRAFTSANDCOLLECTIBLES,
    #[serde(rename = "BABY")]
    BABY,
    #[serde(rename = "BEAUTY_AND_FRAGRANCES")]
    BEAUTYANDFRAGRANCES,
    #[serde(rename = "BOOKS_AND_MAGAZINES")]
    BOOKSANDMAGAZINES,
    #[serde(rename = "BUSINESS_TO_BUSINESS")]
    BUSINESSTOBUSINESS,
    #[serde(rename = "CLOTHING_ACCESSORIES_AND_SHOES")]
    CLOTHINGACCESSORIESANDSHOES,
    #[serde(rename = "COMPUTERS_ACCESSORIES_AND_SERVICES")]
    COMPUTERSACCESSORIESANDSERVICES,
    #[serde(rename = "EDUCATION")]
    EDUCATION,
    #[serde(rename = "ELECTRONICS_AND_TELECOM")]
    ELECTRONICSANDTELECOM,
    #[serde(rename = "ENTERTAINMENT_AND_MEDIA")]
    ENTERTAINMENTANDMEDIA,
    #[serde(rename = "FINANCIAL_SERVICES_AND_PRODUCTS")]
    FINANCIALSERVICESANDPRODUCTS,
    #[serde(rename = "FOOD_RETAIL_AND_SERVICE")]
    FOODRETAILANDSERVICE,
    #[serde(rename = "GIFTS_AND_FLOWERS")]
    GIFTSANDFLOWERS,
    #[serde(rename = "HEALTH_AND_PERSONAL_CARE")]
    HEALTHANDPERSONALCARE,
    #[serde(rename = "HOME_AND_GARDEN")]
    HOMEANDGARDEN,
    #[serde(rename = "NONPROFIT")]
    NONPROFIT,
    #[serde(rename = "PETS_AND_ANIMALS")]
    PETSANDANIMALS,
    #[serde(rename = "RELIGION_AND_SPIRITUALITY_FOR_PROFIT")]
    RELIGIONANDSPIRITUALITYFORPROFIT,
    #[serde(rename = "RETAIL_NOT_ELSEWHERE_CLASSIFIED")]
    RETAILNOTELSEWHERECLASSIFIED,
    #[serde(rename = "SERVICES_OTHER")]
    SERVICESOTHER,
    #[serde(rename = "SPORTS_AND_OUTDOORS")]
    SPORTSANDOUTDOORS,
    #[serde(rename = "TOYS_AND_HOBBIES")]
    TOYSANDHOBBIES,
    #[serde(rename = "TRAVEL")]
    TRAVEL,
    #[serde(rename = "VEHICLE_SERVICE_AND_ACCESSORIES")]
    VEHICLESERVICEANDACCESSORIES,
    #[serde(rename = "PROFESSIONAL_SERVICES")]
    PROFESSIONALSERVICES,
    #[serde(rename = "RETAIL_BARS_AND_RESTAURANTS")]
    RETAILBARSANDRESTAURANTS,
    #[serde(rename = "ENTERTAINMENT_AND_TRAVEL")]
    ENTERTAINMENTANDTRAVEL,
    #[serde(rename = "HEALTH_AND_SOCIAL_CARE")]
    HEALTHANDSOCIALCARE,
    #[serde(rename = "TRANSPORT_AND_VEHICLES")]
    TRANSPORTANDVEHICLES,
    #[serde(rename = "CONSTRUCTION_TRADES_AND_CLEANING")]
    CONSTRUCTIONTRADESANDCLEANING,
    #[serde(rename = "PROPERTY")]
    PROPERTY,
    #[serde(rename = "EXERCISE_AND_FITNESS")]
    EXERCISEANDFITNESS,
    #[serde(rename = "EDUCATION_AND_SKILLS")]
    EDUCATIONANDSKILLS,
    #[serde(rename = "NON_PROFIT")]
    NONPROFIT,
    #[serde(rename = "MANUFACTURING_RND_AND_AGRICULTURE")]
    MANUFACTURINGRNDANDAGRICULTURE,
}

impl Default for BusinessCategory {
    fn default() -> BusinessCategory {
        Self::NOTPROVIDED
    }
}
/// Business subcategory
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
)]
pub enum BusinessSubCategory {
    #[serde(rename = "NOT_PROVIDED")]
    NOTPROVIDED,
    #[serde(rename = "ART_AND_CRAFT_SUPPLIES")]
    ARTANDCRAFTSUPPLIES,
    #[serde(rename = "ART_DEALERS_AND_GALLERIES")]
    ARTDEALERSANDGALLERIES,
    #[serde(rename = "CAMERA_AND_PHOTOGRAPHIC_SUPPLIES")]
    CAMERAANDPHOTOGRAPHICSUPPLIES,
    #[serde(rename = "DIGITAL_ART")]
    DIGITALART,
    #[serde(rename = "MEMORABILIA")]
    MEMORABILIA,
    #[serde(rename = "MUSIC_STORE_INSTRUMENTS_AND_SHEET_MUSIC")]
    MUSICSTOREINSTRUMENTSANDSHEETMUSIC,
    #[serde(rename = "SEWING_NEEDLEWORK_AND_FABRICS")]
    SEWINGNEEDLEWORKANDFABRICS,
    #[serde(rename = "STAMP_AND_COIN")]
    STAMPANDCOIN,
    #[serde(rename = "STATIONARY_PRINTING_AND_WRITING_PAPER")]
    STATIONARYPRINTINGANDWRITINGPAPER,
    #[serde(rename = "VINTAGE_AND_COLLECTIBLES")]
    VINTAGEANDCOLLECTIBLES,
    #[serde(rename = "CLOTHING")]
    CLOTHING,
    #[serde(rename = "FURNITURE")]
    FURNITURE,
    #[serde(rename = "BABY_PRODUCTS_OTHER")]
    BABYPRODUCTSOTHER,
    #[serde(rename = "SAFETY_AND_HEALTH")]
    SAFETYANDHEALTH,
    #[serde(rename = "BATH_AND_BODY")]
    BATHANDBODY,
    #[serde(rename = "FRAGRANCES_AND_PERFUMES")]
    FRAGRANCESANDPERFUMES,
    #[serde(rename = "MAKEUP_AND_COSMETICS")]
    MAKEUPANDCOSMETICS,
    #[serde(rename = "AUDIO_BOOKS")]
    AUDIOBOOKS,
    #[serde(rename = "DIGITAL_CONTENT")]
    DIGITALCONTENT,
    #[serde(rename = "EDUCATIONAL_AND_TEXTBOOKS")]
    EDUCATIONALANDTEXTBOOKS,
    #[serde(rename = "FICTION_AND_NONFICTION")]
    FICTIONANDNONFICTION,
    #[serde(rename = "MAGAZINES")]
    MAGAZINES,
    #[serde(rename = "BOOKS_PUBLISHING_AND_PRINTING")]
    BOOKSPUBLISHINGANDPRINTING,
    #[serde(rename = "RARE_AND_USED_BOOKS")]
    RAREANDUSEDBOOKS,
    #[serde(rename = "ACCOUNTING")]
    ACCOUNTING,
    #[serde(rename = "ADVERTISING")]
    ADVERTISING,
    #[serde(rename = "AGRICULTURAL")]
    AGRICULTURAL,
    #[serde(
        rename = "ARCHITECTURAL_ENGINEERING_AND_SURVEYING_SERVICES"
    )]
    ARCHITECTURALENGINEERINGANDSURVEYINGSERVICES,
    #[serde(rename = "CHEMICALS_AND_ALLIED_PRODUCTS")]
    CHEMICALSANDALLIEDPRODUCTS,
    #[serde(rename = "COMMERCIAL_PHOTOGRAPHY_ART_AND_GRAPHICS")]
    COMMERCIALPHOTOGRAPHYARTANDGRAPHICS,
    #[serde(rename = "CONSTRUCTION")]
    CONSTRUCTION,
    #[serde(rename = "CONSULTING_SERVICES")]
    CONSULTINGSERVICES,
    #[serde(rename = "EDUCATIONAL_SERVICES")]
    EDUCATIONALSERVICES,
    #[serde(rename = "EQUIPMENT_RENTALS_AND_LEASING_SERVICES")]
    EQUIPMENTRENTALSANDLEASINGSERVICES,
    #[serde(rename = "EQUIPMENT_REPAIR_SERVICES")]
    EQUIPMENTREPAIRSERVICES,
    #[serde(rename = "HIRING_SERVICES")]
    HIRINGSERVICES,
    #[serde(rename = "INDUSTRIAL_AND_MANUFACTURING_SUPPLIES")]
    INDUSTRIALANDMANUFACTURINGSUPPLIES,
    #[serde(rename = "MAILING_LISTS")]
    MAILINGLISTS,
    #[serde(rename = "MARKETING")]
    MARKETING,
    #[serde(rename = "MULTILEVEL_MARKETING")]
    MULTILEVELMARKETING,
    #[serde(rename = "OFFICE_AND_COMMERCIAL_FURNITURE")]
    OFFICEANDCOMMERCIALFURNITURE,
    #[serde(rename = "OFFICE_SUPPLIES_AND_EQUIPMENT")]
    OFFICESUPPLIESANDEQUIPMENT,
    #[serde(rename = "PUBLISHING_AND_PRINTING")]
    PUBLISHINGANDPRINTING,
    #[serde(rename = "QUICK_COPY_AND_REPRODUCTION_SERVICES")]
    QUICKCOPYANDREPRODUCTIONSERVICES,
    #[serde(rename = "SHIPPING_AND_PACKING")]
    SHIPPINGANDPACKING,
    #[serde(rename = "STENOGRAPHIC_AND_SECRETARIAL_SUPPORT_SERVICES")]
    STENOGRAPHICANDSECRETARIALSUPPORTSERVICES,
    #[serde(rename = "WHOLESALE")]
    WHOLESALE,
    #[serde(rename = "CHILDRENS_CLOTHING")]
    CHILDRENSCLOTHING,
    #[serde(rename = "MENS_CLOTHING")]
    MENSCLOTHING,
    #[serde(rename = "WOMENS_CLOTHING")]
    WOMENSCLOTHING,
    #[serde(rename = "SHOES")]
    SHOES,
    #[serde(rename = "MILITARY_AND_CIVIL_SERVICE_UNIFORMS")]
    MILITARYANDCIVILSERVICEUNIFORMS,
    #[serde(rename = "ACCESSORIES")]
    ACCESSORIES,
    #[serde(rename = "RETAIL_FINE_JEWELRY_AND_WATCHES")]
    RETAILFINEJEWELRYANDWATCHES,
    #[serde(rename = "WHOLESALE_PRECIOUS_STONES_AND_METALS")]
    WHOLESALEPRECIOUSSTONESANDMETALS,
    #[serde(rename = "FASHION_JEWELLERY")]
    FASHIONJEWELLERY,
    #[serde(rename = "COMPUTER_AND_DATA_PROCESSING_SERVICES")]
    COMPUTERANDDATAPROCESSINGSERVICES,
    #[serde(rename = "DESKTOPS_LAPTOPS_AND_NOTEBOOKS")]
    DESKTOPSLAPTOPSANDNOTEBOOKS,
    #[serde(rename = "COMPUTER_DIGITAL_CONTENT")]
    COMPUTERDIGITALCONTENT,
    #[serde(rename = "ECOMMERCE_SERVICES")]
    ECOMMERCESERVICES,
    #[serde(rename = "MAINTENANCE_AND_REPAIR_SERVICES")]
    MAINTENANCEANDREPAIRSERVICES,
    #[serde(rename = "MONITORS_AND_PROJECTORS")]
    MONITORSANDPROJECTORS,
    #[serde(rename = "NETWORKING")]
    NETWORKING,
    #[serde(rename = "ONLINE_GAMING")]
    ONLINEGAMING,
    #[serde(rename = "PARTS_AND_ACCESSORIES")]
    PARTSANDACCESSORIES,
    #[serde(rename = "PERIPHERALS")]
    PERIPHERALS,
    #[serde(rename = "SOFTWARE")]
    SOFTWARE,
    #[serde(rename = "TRAINING_SERVICES")]
    TRAININGSERVICES,
    #[serde(rename = "WEB_HOSTING_AND_DESIGN")]
    WEBHOSTINGANDDESIGN,
    #[serde(rename = "BUSINESS_AND_SECRETARIAL_SCHOOLS")]
    BUSINESSANDSECRETARIALSCHOOLS,
    #[serde(rename = "CHILD_DAYCARE_SERVICES")]
    CHILDDAYCARESERVICES,
    #[serde(rename = "DANCE_HALLS_STUDIOS_AND_SCHOOLS")]
    DANCEHALLSSTUDIOSANDSCHOOLS,
    #[serde(rename = "VOCATIONAL_AND_TRADE_SCHOOLS")]
    VOCATIONALANDTRADESCHOOLS,
    #[serde(rename = "CAMERAS_CAMCORDERS_AND_EQUIPMENT")]
    CAMERASCAMCORDERSANDEQUIPMENT,
    #[serde(rename = "CELL_PHONES_PDAS_AND_PAGERS")]
    CELLPHONESPDASANDPAGERS,
    #[serde(rename = "GENERAL_ELECTRONIC_ACCESSORIES")]
    GENERALELECTRONICACCESSORIES,
    #[serde(rename = "HOME_AUDIO")]
    HOMEAUDIO,
    #[serde(rename = "HOME_ELECTRONICS")]
    HOMEELECTRONICS,
    #[serde(rename = "SECURITY_AND_SURVEILLANCE")]
    SECURITYANDSURVEILLANCE,
    #[serde(rename = "TELECOMMUNICATION_EQUIPMENT_AND_SALES")]
    TELECOMMUNICATIONEQUIPMENTANDSALES,
    #[serde(rename = "TELECOMMUNICATION_SERVICES")]
    TELECOMMUNICATIONSERVICES,
    #[serde(rename = "TELEPHONE_CARDS")]
    TELEPHONECARDS,
    #[serde(rename = "ENTERTAINMENT_MEMORABILIA")]
    ENTERTAINMENTMEMORABILIA,
    #[serde(rename = "MOVIE_TICKETS")]
    MOVIETICKETS,
    #[serde(rename = "MOVIES_DVDS_VIDEOTAPES")]
    MOVIESDVDSVIDEOTAPES,
    #[serde(rename = "MUSIC_CDS_CASSETTES_AND_ALBUMS")]
    MUSICCDSCASSETTESANDALBUMS,
    #[serde(rename = "CABLE_SATELLITE_AND_OTHER_PAY_TV_AND_RADIO")]
    CABLESATELLITEANDOTHERPAYTVANDRADIO,
    #[serde(rename = "CONCERT_TICKETS")]
    CONCERTTICKETS,
    #[serde(rename = "THEATER_TICKETS")]
    THEATERTICKETS,
    #[serde(rename = "TOYS_AND_GAMES")]
    TOYSANDGAMES,
    #[serde(rename = "ENTERTAINMENT_DIGITAL_CONTENT")]
    ENTERTAINMENTDIGITALCONTENT,
    #[serde(rename = "ENTERTAINERS")]
    ENTERTAINERS,
    #[serde(rename = "ONLINE_GAMES")]
    ONLINEGAMES,
    #[serde(rename = "VIDEO_GAMES_AND_SYSTEMS")]
    VIDEOGAMESANDSYSTEMS,
    #[serde(rename = "FINANCIAL_ACCOUNTING")]
    FINANCIALACCOUNTING,
    #[serde(rename = "DEBT_COUNSELING_SERVICE")]
    DEBTCOUNSELINGSERVICE,
    #[serde(rename = "FINANCIAL_AND_INVESTMENT_ADVICE")]
    FINANCIALANDINVESTMENTADVICE,
    #[serde(rename = "REAL_ESTATE_AGENT")]
    REALESTATEAGENT,
    #[serde(rename = "RENTAL_PROPERTY_MANAGEMENT")]
    RENTALPROPERTYMANAGEMENT,
    #[serde(rename = "ALCOHOLIC_BEVERAGES")]
    ALCOHOLICBEVERAGES,
    #[serde(rename = "CATERING_SERVICES")]
    CATERINGSERVICES,
    #[serde(rename = "COFFEE_AND_TEA")]
    COFFEEANDTEA,
    #[serde(rename = "GOURMET_FOODS")]
    GOURMETFOODS,
    #[serde(rename = "SPECIALTY_AND_MISCELLANEOUS_FOOD_STORES")]
    SPECIALTYANDMISCELLANEOUSFOODSTORES,
    #[serde(rename = "RESTAURANT")]
    RESTAURANT,
    #[serde(rename = "TOBACCO")]
    TOBACCO,
    #[serde(rename = "VITAMINS_AND_SUPPLEMENTS")]
    VITAMINSANDSUPPLEMENTS,
    #[serde(rename = "FLORIST")]
    FLORIST,
    #[serde(rename = "GIFT_CARD_NOVELTY_AND_SOUVENIR_SHOPS")]
    GIFTCARDNOVELTYANDSOUVENIRSHOPS,
    #[serde(rename = "GIFTS_GOURMET_FOODS")]
    GIFTSGOURMETFOODS,
    #[serde(rename = "NURSERY_PLANTS_AND_FLOWERS")]
    NURSERYPLANTSANDFLOWERS,
    #[serde(rename = "PARTY_SUPPLIES")]
    PARTYSUPPLIES,
    #[serde(rename = "DENTAL_CARE")]
    DENTALCARE,
    #[serde(rename = "MEDICAL_CARE")]
    MEDICALCARE,
    #[serde(rename = "MEDICAL_EQUIPMENT_AND_SUPPLIES")]
    MEDICALEQUIPMENTANDSUPPLIES,
    #[serde(rename = "VISION_CARE")]
    VISIONCARE,
    #[serde(rename = "HEALTH_VITAMINS_AND_SUPPLEMENTS")]
    HEALTHVITAMINSANDSUPPLEMENTS,
    #[serde(rename = "APPLIANCES")]
    APPLIANCES,
    #[serde(rename = "HOME_ART_DEALERS_AND_GALLERIES")]
    HOMEARTDEALERSANDGALLERIES,
    #[serde(rename = "BED_AND_BATH")]
    BEDANDBATH,
    #[serde(rename = "CONSTRUCTION_MATERIAL")]
    CONSTRUCTIONMATERIAL,
    #[serde(rename = "DRAPERY_WINDOW_COVERING_AND_UPHOLSTERY")]
    DRAPERYWINDOWCOVERINGANDUPHOLSTERY,
    #[serde(rename = "EXTERMINATING_AND_DISINFECTING_SERVICES")]
    EXTERMINATINGANDDISINFECTINGSERVICES,
    #[serde(rename = "FIREPLACE_AND_FIREPLACE_SCREENS")]
    FIREPLACEANDFIREPLACESCREENS,
    #[serde(rename = "HOME_FURNITURE")]
    HOMEFURNITURE,
    #[serde(rename = "GARDEN_SUPPLIES")]
    GARDENSUPPLIES,
    #[serde(rename = "GLASS_PAINT_AND_WALLPAPER")]
    GLASSPAINTANDWALLPAPER,
    #[serde(rename = "HARDWARE_AND_TOOLS")]
    HARDWAREANDTOOLS,
    #[serde(rename = "HOME_DECOR")]
    HOMEDECOR,
    #[serde(rename = "HOUSEWARES")]
    HOUSEWARES,
    #[serde(rename = "KITCHENWARE")]
    KITCHENWARE,
    #[serde(rename = "LANDSCAPING")]
    LANDSCAPING,
    #[serde(rename = "RUGS_AND_CARPETS")]
    RUGSANDCARPETS,
    #[serde(rename = "SECURITY_AND_SURVEILLANCE_EQUIPMENT")]
    SECURITYANDSURVEILLANCEEQUIPMENT,
    #[serde(rename = "SWIMMING_POOLS_AND_SPAS")]
    SWIMMINGPOOLSANDSPAS,
    #[serde(rename = "CHARITY")]
    CHARITY,
    #[serde(rename = "POLITICAL")]
    POLITICAL,
    #[serde(rename = "RELIGIOUS")]
    RELIGIOUS,
    #[serde(rename = "OTHER")]
    OTHER,
    #[serde(rename = "PERSONAL")]
    PERSONAL,
    #[serde(rename = "EDUCATIONAL")]
    EDUCATIONAL,
    #[serde(rename = "MEDICATION_AND_SUPPLEMENTS")]
    MEDICATIONANDSUPPLEMENTS,
    #[serde(rename = "PET_SHOPS_PET_FOOD_AND_SUPPLIES")]
    PETSHOPSPETFOODANDSUPPLIES,
    #[serde(rename = "SPECIALTY_OR_RARE_PETS")]
    SPECIALTYORRAREPETS,
    #[serde(rename = "VETERINARY_SERVICES")]
    VETERINARYSERVICES,
    #[serde(rename = "MEMBERSHIP_SERVICES")]
    MEMBERSHIPSERVICES,
    #[serde(rename = "MERCHANDISE")]
    MERCHANDISE,
    #[serde(rename = "SERVICES_NOT_ELSEWHERE_CLASSIFIED")]
    SERVICESNOTELSEWHERECLASSIFIED,
    #[serde(rename = "RETAIL_CHEMICALS_AND_ALLIED_PRODUCTS")]
    RETAILCHEMICALSANDALLIEDPRODUCTS,
    #[serde(rename = "DEPARTMENT_STORE")]
    DEPARTMENTSTORE,
    #[serde(rename = "DISCOUNT_STORE")]
    DISCOUNTSTORE,
    #[serde(rename = "DURABLE_GOODS")]
    DURABLEGOODS,
    #[serde(rename = "NONDURABLE_GOODS")]
    NONDURABLEGOODS,
    #[serde(rename = "USED_AND_SECONDHAND_STORE")]
    USEDANDSECONDHANDSTORE,
    #[serde(rename = "VARIETY_STORE")]
    VARIETYSTORE,
    #[serde(rename = "SERVICES_ADVERTISING")]
    SERVICESADVERTISING,
    #[serde(rename = "SHOPPING_SERVICES_AND_BUYING_CLUBS")]
    SHOPPINGSERVICESANDBUYINGCLUBS,
    #[serde(rename = "CAREER_SERVICES")]
    CAREERSERVICES,
    #[serde(rename = "CARPENTRY")]
    CARPENTRY,
    #[serde(rename = "CHILD_CARE_SERVICES")]
    CHILDCARESERVICES,
    #[serde(rename = "CLEANING_AND_MAINTENANCE")]
    CLEANINGANDMAINTENANCE,
    #[serde(rename = "COMMERCIAL_PHOTOGRAPHY")]
    COMMERCIALPHOTOGRAPHY,
    #[serde(rename = "SERVICES_COMPUTER_AND_DATA_PROCESSING_SERVICES")]
    SERVICESCOMPUTERANDDATAPROCESSINGSERVICES,
    #[serde(rename = "COMPUTER_NETWORK_SERVICES")]
    COMPUTERNETWORKSERVICES,
    #[serde(rename = "SERVICES_CONSULTING_SERVICES")]
    SERVICESCONSULTINGSERVICES,
    #[serde(rename = "COUNSELING_SERVICES")]
    COUNSELINGSERVICES,
    #[serde(rename = "COURIER_SERVICES")]
    COURIERSERVICES,
    #[serde(rename = "SERVICES_DENTAL_CARE")]
    SERVICESDENTALCARE,
    #[serde(rename = "SERVICES_ECOMMERCE_SERVICES")]
    SERVICESECOMMERCESERVICES,
    #[serde(rename = "ELECTRICAL_AND_SMALL_APPLIANCE_REPAIR")]
    ELECTRICALANDSMALLAPPLIANCEREPAIR,
    #[serde(rename = "ENTERTAINMENT")]
    ENTERTAINMENT,
    #[serde(rename = "EQUIPMENT_RENTAL_AND_LEASING_SERVICES")]
    EQUIPMENTRENTALANDLEASINGSERVICES,
    #[serde(rename = "EVENT_AND_WEDDING_PLANNING")]
    EVENTANDWEDDINGPLANNING,
    #[serde(rename = "GENERAL_CONTRACTORS")]
    GENERALCONTRACTORS,
    #[serde(rename = "GRAPHIC_AND_COMMERCIAL_DESIGN")]
    GRAPHICANDCOMMERCIALDESIGN,
    #[serde(rename = "HEALTH_AND_BEAUTY_SPAS")]
    HEALTHANDBEAUTYSPAS,
    #[serde(rename = "IDS_LICENSES_AND_PASSPORTS")]
    IDSLICENSESANDPASSPORTS,
    #[serde(rename = "IMPORTING_AND_EXPORTING")]
    IMPORTINGANDEXPORTING,
    #[serde(rename = "INFORMATION_RETRIEVAL_SERVICES")]
    INFORMATIONRETRIEVALSERVICES,
    #[serde(rename = "LANDSCAPING_AND_HORTICULTURAL")]
    LANDSCAPINGANDHORTICULTURAL,
    #[serde(rename = "LEGAL_SERVICES_AND_ATTORNEYS")]
    LEGALSERVICESANDATTORNEYS,
    #[serde(rename = "LOCAL_DELIVERY_SERVICE")]
    LOCALDELIVERYSERVICE,
    #[serde(rename = "SERVICES_MEDICAL_CARE")]
    SERVICESMEDICALCARE,
    #[serde(rename = "MEMBERSHIP_CLUBS_AND_ORGANIZATIONS")]
    MEMBERSHIPCLUBSANDORGANIZATIONS,
    #[serde(rename = "SERVICES_MISC_PUBLISHING_AND_PRINTING")]
    SERVICESMISCPUBLISHINGANDPRINTING,
    #[serde(rename = "MOVING_AND_STORAGE")]
    MOVINGANDSTORAGE,
    #[serde(rename = "PHOTOFINISHING")]
    PHOTOFINISHING,
    #[serde(rename = "PHOTOGRAPHIC_STUDIOS__PORTRAITS")]
    PHOTOGRAPHICSTUDIOSPORTRAITS,
    #[serde(rename = "PROTECTIVE_AND_SECURITY_SERVICES")]
    PROTECTIVEANDSECURITYSERVICES,
    #[serde(rename = "SERVICES_QUICK_COPY_AND_REPRODUCTION_SERVICES")]
    SERVICESQUICKCOPYANDREPRODUCTIONSERVICES,
    #[serde(rename = "RADIO_TELEVISION_AND_STEREO_REPAIR")]
    RADIOTELEVISIONANDSTEREOREPAIR,
    #[serde(rename = "REAL_ESTATE_AGENT_")]
    REALESTATEAGENT,
    #[serde(rename = "SERVICES_RENTAL_PROPERTY_MANAGEMENT")]
    SERVICESRENTALPROPERTYMANAGEMENT,
    #[serde(rename = "REUPHOLSTERY_AND_FURNITURE_REPAIR")]
    REUPHOLSTERYANDFURNITUREREPAIR,
    #[serde(rename = "SERVICES_SERVICES_NOT_ELSEWHERE_CLASSIFIED")]
    SERVICESSERVICESNOTELSEWHERECLASSIFIED,
    #[serde(rename = "SERVICES_SHIPPING_AND_PACKING")]
    SERVICESSHIPPINGANDPACKING,
    #[serde(rename = "SWIMMING_POOL_SERVICES")]
    SWIMMINGPOOLSERVICES,
    #[serde(rename = "TAILORS_AND_ALTERATIONS")]
    TAILORSANDALTERATIONS,
    #[serde(rename = "TELECOMMUNICATION_SERVICE")]
    TELECOMMUNICATIONSERVICE,
    #[serde(rename = "UTILITIES")]
    UTILITIES,
    #[serde(rename = "SERVICES_VISION_CARE")]
    SERVICESVISIONCARE,
    #[serde(rename = "WATCH_CLOCK_AND_JEWELRY_REPAIR")]
    WATCHCLOCKANDJEWELRYREPAIR,
    #[serde(rename = "ATHLETIC_SHOES")]
    ATHLETICSHOES,
    #[serde(rename = "BICYCLE_SHOP_SERVICE_AND_REPAIR")]
    BICYCLESHOPSERVICEANDREPAIR,
    #[serde(rename = "BOATING_SAILING_AND_ACCESSORIES")]
    BOATINGSAILINGANDACCESSORIES,
    #[serde(rename = "CAMPING_AND_OUTDOORS")]
    CAMPINGANDOUTDOORS,
    #[serde(rename = "SPORTS_DANCE_HALLS_STUDIOS_AND_SCHOOLS")]
    SPORTSDANCEHALLSSTUDIOSANDSCHOOLS,
    #[serde(rename = "EXERCISE_AND_FITNESS")]
    EXERCISEANDFITNESS,
    #[serde(rename = "FAN_GEAR_AND_MEMORABILIA")]
    FANGEARANDMEMORABILIA,
    #[serde(rename = "HUNTING")]
    HUNTING,
    #[serde(rename = "MARTIAL_ARTS_WEAPONS")]
    MARTIALARTSWEAPONS,
    #[serde(rename = "SPORT_GAMES_AND_TOYS")]
    SPORTGAMESANDTOYS,
    #[serde(rename = "SPORTING_EQUIPMENT")]
    SPORTINGEQUIPMENT,
    #[serde(rename = "SPORTS_SWIMMING_POOLS_AND_SPAS")]
    SPORTSSWIMMINGPOOLSANDSPAS,
    #[serde(rename = "ARTS_AND_CRAFTS")]
    ARTSANDCRAFTS,
    #[serde(rename = "HOBBIES_CAMERA_AND_PHOTOGRAPHIC_SUPPLIES")]
    HOBBIESCAMERAANDPHOTOGRAPHICSUPPLIES,
    #[serde(rename = "HOBBY_TOY_AND_GAME_SHOPS")]
    HOBBYTOYANDGAMESHOPS,
    #[serde(rename = "HOBBIES_MEMORABILIA")]
    HOBBIESMEMORABILIA,
    #[serde(rename = "MUSIC_STORE__INSTRUMENTS_AND_SHEET_MUSIC")]
    MUSICSTOREINSTRUMENTSANDSHEETMUSIC,
    #[serde(rename = "HOBBIES_STAMP_AND_COIN")]
    HOBBIESSTAMPANDCOIN,
    #[serde(rename = "HOBBIES_STATIONARY_PRINTING_AND_WRITING_PAPER")]
    HOBBIESSTATIONARYPRINTINGANDWRITINGPAPER,
    #[serde(rename = "HOBBIES_VINTAGE_AND_COLLECTIBLES")]
    HOBBIESVINTAGEANDCOLLECTIBLES,
    #[serde(rename = "HOBBIES_VIDEO_GAMES_AND_SYSTEMS")]
    HOBBIESVIDEOGAMESANDSYSTEMS,
    #[serde(rename = "AIRLINE")]
    AIRLINE,
    #[serde(rename = "AUTO_RENTAL")]
    AUTORENTAL,
    #[serde(rename = "BUS_LINE")]
    BUSLINE,
    #[serde(rename = "CRUISES")]
    CRUISES,
    #[serde(rename = "LODGING_AND_ACCOMMODATIONS")]
    LODGINGANDACCOMMODATIONS,
    #[serde(rename = "LUGGAGE_AND_LEATHER_GOODS")]
    LUGGAGEANDLEATHERGOODS,
    #[serde(rename = "RECREATIONAL_SERVICES")]
    RECREATIONALSERVICES,
    #[serde(rename = "SPORTING_AND_RECREATION_CAMPS")]
    SPORTINGANDRECREATIONCAMPS,
    #[serde(rename = "TAXICABS_AND_LIMOUSINES")]
    TAXICABSANDLIMOUSINES,
    #[serde(rename = "TIMESHARES")]
    TIMESHARES,
    #[serde(rename = "TOURS")]
    TOURS,
    #[serde(rename = "TRAILER_PARKS_OR_CAMPGROUNDS")]
    TRAILERPARKSORCAMPGROUNDS,
    #[serde(rename = "TRANSPORTATION_SERVICES__OTHER")]
    TRANSPORTATIONSERVICESOTHER,
    #[serde(rename = "TRAVEL_AGENCY")]
    TRAVELAGENCY,
    #[serde(rename = "NEW_PARTS_AND_SUPPLIES__MOTOR_VEHICLE")]
    NEWPARTSANDSUPPLIESMOTORVEHICLE,
    #[serde(rename = "USED_PARTS__MOTOR_VEHICLE")]
    USEDPARTSMOTORVEHICLE,
    #[serde(rename = "AUDIO_AND_VIDEO")]
    AUDIOANDVIDEO,
    #[serde(rename = "AUTO_BODY_REPAIR_AND_PAINT")]
    AUTOBODYREPAIRANDPAINT,
    #[serde(rename = "SERVICES_AUTO_RENTAL")]
    SERVICESAUTORENTAL,
    #[serde(rename = "AUTO_SERVICE")]
    AUTOSERVICE,
    #[serde(rename = "AUTOMOTIVE_TIRE_SUPPLY_AND_SERVICE")]
    AUTOMOTIVETIRESUPPLYANDSERVICE,
    #[serde(rename = "BOAT_RENTAL_AND_LEASES")]
    BOATRENTALANDLEASES,
    #[serde(rename = "CAR_WASH")]
    CARWASH,
    #[serde(rename = "MOTOR_HOME_AND_RECREATIONAL_VEHICLE_RENTAL")]
    MOTORHOMEANDRECREATIONALVEHICLERENTAL,
    #[serde(rename = "TOOLS_AND_EQUIPMENT")]
    TOOLSANDEQUIPMENT,
    #[serde(rename = "TOWING_SERVICE")]
    TOWINGSERVICE,
    #[serde(rename = "TRUCK_AND_UTILITY_TRAILER_RENTAL")]
    TRUCKANDUTILITYTRAILERRENTAL,
    #[serde(rename = "VEHICLE_ACCESSORIES")]
    VEHICLEACCESSORIES,
    #[serde(rename = "CLEANING")]
    CLEANING,
    #[serde(rename = "DECORATING")]
    DECORATING,
    #[serde(rename = "ELECTRICIAN")]
    ELECTRICIAN,
    #[serde(rename = "PLUMBER")]
    PLUMBER,
    #[serde(rename = "GAS_AND_HEATING")]
    GASANDHEATING,
    #[serde(rename = "CARPENTRY_TRADE")]
    CARPENTRYTRADE,
    #[serde(rename = "ROOFING")]
    ROOFING,
    #[serde(rename = "GARDENING_AND_TREE_SURGERY")]
    GARDENINGANDTREESURGERY,
    #[serde(rename = "GENERAL_CONTRACTOR")]
    GENERALCONTRACTOR,
    #[serde(rename = "CONSTRUCTION_SUPPLIER")]
    CONSTRUCTIONSUPPLIER,
    #[serde(rename = "WASTE_AND_RECYCLING")]
    WASTEANDRECYCLING,
    #[serde(rename = "SCRAP_METAL")]
    SCRAPMETAL,
    #[serde(rename = "SITE_AND_BUILDING_MANAGEMENT")]
    SITEANDBUILDINGMANAGEMENT,
    #[serde(rename = "CONSTRUCTION_TRADES_AND_CLEANING_OTHER")]
    CONSTRUCTIONTRADESANDCLEANINGOTHER,
    #[serde(rename = "PERSONAL_TUTOR")]
    PERSONALTUTOR,
    #[serde(rename = "MUSIC_TEACHERS")]
    MUSICTEACHERS,
    #[serde(rename = "PROFESSIONAL_TRAINER")]
    PROFESSIONALTRAINER,
    #[serde(rename = "PUBLIC_SPEAKING")]
    PUBLICSPEAKING,
    #[serde(rename = "NURSERY")]
    NURSERY,
    #[serde(rename = "CHILDMINDER")]
    CHILDMINDER,
    #[serde(rename = "NANNY_OR_AU_PAIR")]
    NANNYORAUPAIR,
    #[serde(rename = "CHILDRENS_ACTIVITIES")]
    CHILDRENSACTIVITIES,
    #[serde(rename = "STUDENT_RECRUITMENT")]
    STUDENTRECRUITMENT,
    #[serde(rename = "STUDENT_SUPPORT")]
    STUDENTSUPPORT,
    #[serde(rename = "SCHOOLS_COLLEGES_AND_TRAINING")]
    SCHOOLSCOLLEGESANDTRAINING,
    #[serde(rename = "EDUCATION_AND_SKILLS_OTHER")]
    EDUCATIONANDSKILLSOTHER,
    #[serde(rename = "DIGITAL_CONTENT_OR_GAMES")]
    DIGITALCONTENTORGAMES,
    #[serde(rename = "PROMOTION_AND_PUBLISHING")]
    PROMOTIONANDPUBLISHING,
    #[serde(rename = "CATERING")]
    CATERING,
    #[serde(rename = "ENTERTAINERS_AND_DJS")]
    ENTERTAINERSANDDJS,
    #[serde(rename = "EVENTS_AND_WEDDINGS")]
    EVENTSANDWEDDINGS,
    #[serde(rename = "EVENTS_PRODUCTS")]
    EVENTSPRODUCTS,
    #[serde(rename = "EVENTS_STAFFING_AND_SERVICES")]
    EVENTSSTAFFINGANDSERVICES,
    #[serde(rename = "TRAVEL_AGENT")]
    TRAVELAGENT,
    #[serde(rename = "TOUR_GUIDE")]
    TOURGUIDE,
    #[serde(rename = "LODGING_AND_ACCOMMODATION")]
    LODGINGANDACCOMMODATION,
    #[serde(rename = "TV_AND_RADIO")]
    TVANDRADIO,
    #[serde(rename = "MUSICIAN_OR_GROUPS")]
    MUSICIANORGROUPS,
    #[serde(rename = "ENTERTAINMENT_AND_TRAVEL_OTHER")]
    ENTERTAINMENTANDTRAVELOTHER,
    #[serde(rename = "PERSONAL_TRAINER")]
    PERSONALTRAINER,
    #[serde(rename = "SPORTS_COACH")]
    SPORTSCOACH,
    #[serde(rename = "SPORTS_CLUB")]
    SPORTSCLUB,
    #[serde(rename = "SPORTS_AND_FITNESS_VENUE")]
    SPORTSANDFITNESSVENUE,
    #[serde(rename = "GYM_OPERATOR")]
    GYMOPERATOR,
    #[serde(rename = "CLASS_INSTRUCTOR")]
    CLASSINSTRUCTOR,
    #[serde(rename = "EXERCISE_AND_FITNESS_OTHER")]
    EXERCISEANDFITNESSOTHER,
    #[serde(rename = "DOCTOR_NURSE_OR_MIDWIFE")]
    DOCTORNURSEORMIDWIFE,
    #[serde(rename = "PHARMACY")]
    PHARMACY,
    #[serde(rename = "PERSONAL_AND_SOCIAL_CARE")]
    PERSONALANDSOCIALCARE,
    #[serde(rename = "PHYSIOTHERAPIST")]
    PHYSIOTHERAPIST,
    #[serde(rename = "NUTRITION_AND_DIET")]
    NUTRITIONANDDIET,
    #[serde(rename = "MENTAL_HEALTH_AND_COUNSELLING")]
    MENTALHEALTHANDCOUNSELLING,
    #[serde(rename = "MEDICAL_EQUIPMENT_AND_SUPPLIERS")]
    MEDICALEQUIPMENTANDSUPPLIERS,
    #[serde(rename = "DENTAL")]
    DENTAL,
    #[serde(rename = "OPTICIAN")]
    OPTICIAN,
    #[serde(rename = "OTHER_MEDICAL_THERAPY")]
    OTHERMEDICALTHERAPY,
    #[serde(rename = "CHIROPRACTOR_OR_OSTEOPATH")]
    CHIROPRACTOROROSTEOPATH,
    #[serde(rename = "PODIATRIST")]
    PODIATRIST,
    #[serde(rename = "COMPLIMENTARY_AND_ALTERNATIVE_MEDICINE")]
    COMPLIMENTARYANDALTERNATIVEMEDICINE,
    #[serde(rename = "HEALTH_AND_SOCIAL_CARE_OTHER")]
    HEALTHANDSOCIALCAREOTHER,
    #[serde(rename = "MANUFACTURING")]
    MANUFACTURING,
    #[serde(rename = "INDUSTRIAL_ENGINEER")]
    INDUSTRIALENGINEER,
    #[serde(rename = "FOOD_OR_DRINK_PRODUCTION")]
    FOODORDRINKPRODUCTION,
    #[serde(rename = "RESEARCH_AND_DEVELOPMENT")]
    RESEARCHANDDEVELOPMENT,
    #[serde(rename = "LIVESTOCK_FARMING")]
    LIVESTOCKFARMING,
    #[serde(rename = "CROP_FARMING")]
    CROPFARMING,
    #[serde(rename = "HORTICULTURE_OR_PLANT_NURSERY")]
    HORTICULTUREORPLANTNURSERY,
    #[serde(rename = "FORESTRY")]
    FORESTRY,
    #[serde(rename = "VETERINARY")]
    VETERINARY,
    #[serde(rename = "SUPPLIER_TO_AGRICULTURE_OR_INDUSTRY")]
    SUPPLIERTOAGRICULTUREORINDUSTRY,
    #[serde(rename = "EQUESTRIAN")]
    EQUESTRIAN,
    #[serde(rename = "ANIMAL_CARE")]
    ANIMALCARE,
    #[serde(rename = "ARMS_MANUFACTURER")]
    ARMSMANUFACTURER,
    #[serde(rename = "MINING")]
    MINING,
    #[serde(rename = "OIL_AND_GAS")]
    OILANDGAS,
    #[serde(rename = "COAL")]
    COAL,
    #[serde(rename = "MANUFACTURING_RND_AND_AGRICULTURE_OTHER")]
    MANUFACTURINGRNDANDAGRICULTUREOTHER,
    #[serde(rename = "ANIMALS")]
    ANIMALS,
    #[serde(rename = "ARTS_CULTURE_AND_HUMANITIES")]
    ARTSCULTUREANDHUMANITIES,
    #[serde(rename = "COMMUNITY_DEVELOPMENT")]
    COMMUNITYDEVELOPMENT,
    #[serde(rename = "EDUCATION")]
    EDUCATION,
    #[serde(rename = "ENVIRONMENT")]
    ENVIRONMENT,
    #[serde(rename = "HEALTH_AND_DISEASE")]
    HEALTHANDDISEASE,
    #[serde(rename = "HUMAN_AND_CIVIL_RIGHTS")]
    HUMANANDCIVILRIGHTS,
    #[serde(rename = "CHILDREN_YOUTH_AND_FAMILY")]
    CHILDRENYOUTHANDFAMILY,
    #[serde(rename = "HOMELESSNESS")]
    HOMELESSNESS,
    #[serde(rename = "INTERNATIONAL")]
    INTERNATIONAL,
    #[serde(rename = "RESEARCH_AND_PUBLIC_POLICY")]
    RESEARCHANDPUBLICPOLICY,
    #[serde(rename = "RELIGION")]
    RELIGION,
    #[serde(rename = "POLITICAL_PARTY")]
    POLITICALPARTY,
    #[serde(rename = "NON_PROFIT_OTHER")]
    NONPROFITOTHER,
    #[serde(rename = "ARCHITECT_STRUCTURAL_ENGINEER_OR_SURVEYOR")]
    ARCHITECTSTRUCTURALENGINEERORSURVEYOR,
    #[serde(rename = "ACCOUNTANCY_AND_BOOKKEEPING")]
    ACCOUNTANCYANDBOOKKEEPING,
    #[serde(rename = "BUSINESS_SERVICES")]
    BUSINESSSERVICES,
    #[serde(rename = "FINANCIAL_OR_INVESTMENT_ADVICE")]
    FINANCIALORINVESTMENTADVICE,
    #[serde(rename = "MORTGAGE_BROKERS")]
    MORTGAGEBROKERS,
    #[serde(rename = "SOFTWARE_AND_IT")]
    SOFTWAREANDIT,
    #[serde(rename = "WEBSITE_DEVELOPMENT")]
    WEBSITEDEVELOPMENT,
    #[serde(rename = "MANAGEMENT_CONSULTANCY")]
    MANAGEMENTCONSULTANCY,
    #[serde(rename = "PROJECT_MANAGEMENT")]
    PROJECTMANAGEMENT,
    #[serde(rename = "MARKETING_ADVERTISING_AND_DESIGN")]
    MARKETINGADVERTISINGANDDESIGN,
    #[serde(rename = "GRAPHIC_DESIGN_AND_ILLUSTRATION")]
    GRAPHICDESIGNANDILLUSTRATION,
    #[serde(rename = "INTERIOR_DESIGN")]
    INTERIORDESIGN,
    #[serde(rename = "RECRUITMENT_AND_HIRING")]
    RECRUITMENTANDHIRING,
    #[serde(rename = "LEGAL")]
    LEGAL,
    #[serde(rename = "PHOTOGRAPHY")]
    PHOTOGRAPHY,
    #[serde(rename = "SECURITY")]
    SECURITY,
    #[serde(rename = "PROBATE_ESTATE_MANAGEMENT")]
    PROBATEESTATEMANAGEMENT,
    #[serde(rename = "PAYROLL_PROVIDER")]
    PAYROLLPROVIDER,
    #[serde(rename = "INSOLVENCY_PRACTITIONER")]
    INSOLVENCYPRACTITIONER,
    #[serde(rename = "TRUST_AND_COMPANY_SERVICE")]
    TRUSTANDCOMPANYSERVICE,
    #[serde(rename = "PROFESSIONAL_SERVICES_OTHER")]
    PROFESSIONALSERVICESOTHER,
    #[serde(rename = "RETAIL_DEPOSIT_TAKER")]
    RETAILDEPOSITTAKER,
    #[serde(rename = "DEBT_MANAGEMENT")]
    DEBTMANAGEMENT,
    #[serde(rename = "DEBT_COLLECTOR")]
    DEBTCOLLECTOR,
    #[serde(rename = "ASSET_FINANCE")]
    ASSETFINANCE,
    #[serde(rename = "BUY_NOW_PAY_LATER")]
    BUYNOWPAYLATER,
    #[serde(rename = "PEER_TO_PEER_LENDING")]
    PEERTOPEERLENDING,
    #[serde(rename = "PAY_DAY_LENDER")]
    PAYDAYLENDER,
    #[serde(rename = "PAWN_BROKER")]
    PAWNBROKER,
    #[serde(rename = "CREDIT_CARDS")]
    CREDITCARDS,
    #[serde(rename = "TERM_LOANS")]
    TERMLOANS,
    #[serde(rename = "MORTGAGE_LENDER")]
    MORTGAGELENDER,
    #[serde(rename = "CLAIMS_MANAGEMENT")]
    CLAIMSMANAGEMENT,
    #[serde(rename = "EMONEY_PREPAID")]
    EMONEYPREPAID,
    #[serde(rename = "INSURANCE")]
    INSURANCE,
    #[serde(rename = "PENSION_PROVIDER")]
    PENSIONPROVIDER,
    #[serde(rename = "CREDIT_REFERENCE_AGENCY")]
    CREDITREFERENCEAGENCY,
    #[serde(rename = "CURRENCY_EXCHANGE")]
    CURRENCYEXCHANGE,
    #[serde(rename = "CRYPTO_EXCHANGE")]
    CRYPTOEXCHANGE,
    #[serde(rename = "COMMODITY_EXCHANGE")]
    COMMODITYEXCHANGE,
    #[serde(rename = "MONEY_TRANSFER")]
    MONEYTRANSFER,
    #[serde(rename = "INVESTMENT_BANK")]
    INVESTMENTBANK,
    #[serde(rename = "FUND_MANAGER")]
    FUNDMANAGER,
    #[serde(rename = "FUND_MANAGEMENT")]
    FUNDMANAGEMENT,
    #[serde(rename = "INTERNATIONAL_FINANCE")]
    INTERNATIONALFINANCE,
    #[serde(rename = "MERCHANT_BANKING")]
    MERCHANTBANKING,
    #[serde(rename = "MARKET_MAKER")]
    MARKETMAKER,
    #[serde(rename = "SHARE_TRADING")]
    SHARETRADING,
    #[serde(rename = "EQUITIES_TRADING")]
    EQUITIESTRADING,
    #[serde(rename = "DERIVATIVES_TRADING")]
    DERIVATIVESTRADING,
    #[serde(rename = "FX_TRADING")]
    FXTRADING,
    #[serde(rename = "INVESTMENT_MANAGEMENT")]
    INVESTMENTMANAGEMENT,
    #[serde(rename = "ASSET_MANAGEMENT")]
    ASSETMANAGEMENT,
    #[serde(rename = "INVESTMENT_DEAL_ARRANGEMENTS")]
    INVESTMENTDEALARRANGEMENTS,
    #[serde(rename = "BEARER_SHARES")]
    BEARERSHARES,
    #[serde(rename = "PROPERTY_OWNER")]
    PROPERTYOWNER,
    #[serde(rename = "PROPERTY_INVESTOR")]
    PROPERTYINVESTOR,
    #[serde(rename = "PROPERTY_INVESTMENT_FUND")]
    PROPERTYINVESTMENTFUND,
    #[serde(rename = "RESIDENTS_ASSOCIATION")]
    RESIDENTSASSOCIATION,
    #[serde(rename = "LEASEHOLD_OR_FREEHOLD")]
    LEASEHOLDORFREEHOLD,
    #[serde(rename = "HOLIDAY_OR_SHORT_TERM_LETS")]
    HOLIDAYORSHORTTERMLETS,
    #[serde(rename = "PROPERTY_REDEVELOPMENT")]
    PROPERTYREDEVELOPMENT,
    #[serde(rename = "ESTATE_AGENT")]
    ESTATEAGENT,
    #[serde(rename = "PROPERTY_MANAGEMENT")]
    PROPERTYMANAGEMENT,
    #[serde(rename = "STORAGE")]
    STORAGE,
    #[serde(rename = "PROPERTY_OTHER")]
    PROPERTYOTHER,
    #[serde(rename = "RESTAURANT_OR_CAFE")]
    RESTAURANTORCAFE,
    #[serde(rename = "TAKEAWAY")]
    TAKEAWAY,
    #[serde(rename = "STREET_FOOD_OR_MARKET_STALL")]
    STREETFOODORMARKETSTALL,
    #[serde(rename = "RETAIL")]
    RETAIL,
    #[serde(rename = "WHOLESALING")]
    WHOLESALING,
    #[serde(rename = "SALONS")]
    SALONS,
    #[serde(rename = "NAIL_PARLOUR")]
    NAILPARLOUR,
    #[serde(rename = "TATTOO_PARLOUR")]
    TATTOOPARLOUR,
    #[serde(rename = "AT_HOME_SERVICES")]
    ATHOMESERVICES,
    #[serde(rename = "LICENSED_RETAIL")]
    LICENSEDRETAIL,
    #[serde(rename = "LICENSED_FOOD_VENUE")]
    LICENSEDFOODVENUE,
    #[serde(rename = "NEWSAGENTS_CONVENIENCE_STORES")]
    NEWSAGENTSCONVENIENCESTORES,
    #[serde(rename = "MOBILE_PHONE_SALES")]
    MOBILEPHONESALES,
    #[serde(rename = "IMPORT_EXPORT")]
    IMPORTEXPORT,
    #[serde(rename = "AUCTION_HOUSE")]
    AUCTIONHOUSE,
    #[serde(rename = "FIREARMS_MILITARY_GOODS")]
    FIREARMSMILITARYGOODS,
    #[serde(rename = "GAMBLING_BETTING")]
    GAMBLINGBETTING,
    #[serde(rename = "JEWELLERY_PRECIOUS_STONES_OR_METALS")]
    JEWELLERYPRECIOUSSTONESORMETALS,
    #[serde(rename = "ANTIQUE_ART_DEALER")]
    ANTIQUEARTDEALER,
    #[serde(rename = "DATING_ESCORT_SERVICES")]
    DATINGESCORTSERVICES,
    #[serde(rename = "ADULT_INDUSTRY")]
    ADULTINDUSTRY,
    #[serde(rename = "ILLEGAL_OR_UNLICENSED_DRUGS")]
    ILLEGALORUNLICENSEDDRUGS,
    #[serde(rename = "RETAIL_BARS_AND_RESTAURANTS_OTHER")]
    RETAILBARSANDRESTAURANTSOTHER,
    #[serde(rename = "HGV_OR_BUS_OR_COACH_DRIVER")]
    HGVORBUSORCOACHDRIVER,
    #[serde(rename = "TAXI_OR_PRIVATE_HIRE_DRIVER")]
    TAXIORPRIVATEHIREDRIVER,
    #[serde(rename = "TRAIN_DRIVER")]
    TRAINDRIVER,
    #[serde(rename = "OTHER_PROFESSIONAL_DRIVER")]
    OTHERPROFESSIONALDRIVER,
    #[serde(rename = "HOME_DELIVERY_AND_COURIER_FIRMS")]
    HOMEDELIVERYANDCOURIERFIRMS,
    #[serde(rename = "HAULAGE_FIRMS")]
    HAULAGEFIRMS,
    #[serde(rename = "TAXI_OR_PRIVATE_HIRE_OPERATOR")]
    TAXIORPRIVATEHIREOPERATOR,
    #[serde(rename = "MINIBUS_OR_COACH_OPERATOR")]
    MINIBUSORCOACHOPERATOR,
    #[serde(rename = "VEHICLE_REPAIR_AND_MAINTENANCE")]
    VEHICLEREPAIRANDMAINTENANCE,
    #[serde(rename = "NEW_CARS_OR_VEHICLE_SALES")]
    NEWCARSORVEHICLESALES,
    #[serde(rename = "VEHICLE_RENTAL")]
    VEHICLERENTAL,
    #[serde(rename = "BICYCLE_SHOPS")]
    BICYCLESHOPS,
    #[serde(rename = "USED_CAR_OR_VEHICLE_SALES")]
    USEDCARORVEHICLESALES,
    #[serde(rename = "VEHICLE_PARTS")]
    VEHICLEPARTS,
    #[serde(rename = "CAR_WASHING")]
    CARWASHING,
    #[serde(rename = "TRANSPORT_AND_VEHICLES_OTHER")]
    TRANSPORTANDVEHICLESOTHER,
}

impl Default for BusinessSubCategory {
    fn default() -> BusinessSubCategory {
        Self::NOTPROVIDED
    }
}
