/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// SpacePhoto : A photo associated to a space

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SpacePhoto {
    /// A text (base 64) encoded picture to associate with the space
    #[serde(rename = "base64EncodedPhoto")]
    pub base64_encoded_photo: String,
}

impl SpacePhoto {
    /// A photo associated to a space
    pub fn new(base64_encoded_photo: String) -> SpacePhoto {
        SpacePhoto {
            base64_encoded_photo,
        }
    }
}
