/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SpendingSpace {
    #[serde(rename = "uid", skip_serializing_if = "Option::is_none")]
    pub uid: Option<String>,
    /// Name of the space
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "balance")]
    pub balance: Box<crate::models::CurrencyAndAmount>,
    /// Card Association Uid
    #[serde(rename = "cardAssociationUid")]
    pub card_association_uid: String,
    /// Sort Order
    #[serde(
        rename = "sortOrder",
        skip_serializing_if = "Option::is_none"
    )]
    pub sort_order: Option<i32>,
    /// Spending Space Type
    #[serde(rename = "spendingSpaceType")]
    pub spending_space_type: SpendingSpaceType,
    /// SpendingSpaceUid
    #[serde(rename = "spaceUid")]
    pub space_uid: String,
}

impl SpendingSpace {
    pub fn new(
        name: String,
        balance: crate::models::CurrencyAndAmount,
        card_association_uid: String,
        spending_space_type: SpendingSpaceType,
        space_uid: String,
    ) -> SpendingSpace {
        SpendingSpace {
            uid: None,
            name,
            balance: Box::new(balance),
            card_association_uid,
            sort_order: None,
            spending_space_type,
            space_uid,
        }
    }
}

/// Spending Space Type
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
)]
pub enum SpendingSpaceType {
    #[serde(rename = "SHOPPING")]
    SHOPPING,
    #[serde(rename = "CHILDCARE")]
    CHILDCARE,
    #[serde(rename = "HELPING_OUT")]
    HELPINGOUT,
    #[serde(rename = "YOUNG_PERSON")]
    YOUNGPERSON,
    #[serde(rename = "EXPENSE")]
    EXPENSE,
    #[serde(rename = "SPARE_CARD")]
    SPARECARD,
    #[serde(rename = "CHILDCARE_V2")]
    CHILDCAREV2,
    #[serde(rename = "SHOPPING_V2")]
    SHOPPINGV2,
    #[serde(rename = "SPARE")]
    SPARE,
}

impl Default for SpendingSpaceType {
    fn default() -> SpendingSpaceType {
        Self::SHOPPING
    }
}
