/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// SpendingSpaceDailyLimitUpdateRequest : Request to update spending space daily limit

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SpendingSpaceDailyLimitUpdateRequest {
    #[serde(rename = "dailySpendingLimit")]
    pub daily_spending_limit: Box<crate::models::Money>,
    #[serde(rename = "dailySpendingLimitNotificationAmount")]
    pub daily_spending_limit_notification_amount:
        Box<crate::models::Money>,
    #[serde(rename = "dailySpendingLimitNotificationEnabled")]
    pub daily_spending_limit_notification_enabled: bool,
}

impl SpendingSpaceDailyLimitUpdateRequest {
    /// Request to update spending space daily limit
    pub fn new(
        daily_spending_limit: crate::models::Money,
        daily_spending_limit_notification_amount: crate::models::Money,
        daily_spending_limit_notification_enabled: bool,
    ) -> SpendingSpaceDailyLimitUpdateRequest {
        SpendingSpaceDailyLimitUpdateRequest {
            daily_spending_limit: Box::new(daily_spending_limit),
            daily_spending_limit_notification_amount: Box::new(
                daily_spending_limit_notification_amount,
            ),
            daily_spending_limit_notification_enabled,
        }
    }
}
