/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// SpendingCategoryBreakdown : Spending insights entry for a spending category

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SpendingCategoryBreakdown {
    /// The category of a transaction
    #[serde(
        rename = "spendingCategory",
        skip_serializing_if = "Option::is_none"
    )]
    pub spending_category: Option<SpendingCategory>,
    /// Amount spent under this spending category
    #[serde(
        rename = "totalSpent",
        skip_serializing_if = "Option::is_none"
    )]
    pub total_spent: Option<f32>,
    /// Amount received under this spending category
    #[serde(
        rename = "totalReceived",
        skip_serializing_if = "Option::is_none"
    )]
    pub total_received: Option<f32>,
    #[serde(
        rename = "netSpend",
        skip_serializing_if = "Option::is_none"
    )]
    pub net_spend: Option<f32>,
    /// Was this an inbound or outbound transaction
    #[serde(
        rename = "netDirection",
        skip_serializing_if = "Option::is_none"
    )]
    pub net_direction: Option<NetDirection>,
    #[serde(
        rename = "currency",
        skip_serializing_if = "Option::is_none"
    )]
    pub currency: Option<Currency>,
    /// Percentage that the netSpend makes up of the sum of the netSpends of breakdowns in the same period with the same netDirection
    #[serde(
        rename = "percentage",
        skip_serializing_if = "Option::is_none"
    )]
    pub percentage: Option<f32>,
    #[serde(
        rename = "transactionCount",
        skip_serializing_if = "Option::is_none"
    )]
    pub transaction_count: Option<i64>,
}

impl SpendingCategoryBreakdown {
    /// Spending insights entry for a spending category
    pub fn new() -> SpendingCategoryBreakdown {
        SpendingCategoryBreakdown {
            spending_category: None,
            total_spent: None,
            total_received: None,
            net_spend: None,
            net_direction: None,
            currency: None,
            percentage: None,
            transaction_count: None,
        }
    }
}

/// The category of a transaction
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
)]
pub enum SpendingCategory {
    #[serde(rename = "BIKE")]
    BIKE,
    #[serde(rename = "BILLS_AND_SERVICES")]
    BILLSANDSERVICES,
    #[serde(rename = "BUCKET_LIST")]
    BUCKETLIST,
    #[serde(rename = "CAR")]
    CAR,
    #[serde(rename = "CASH")]
    CASH,
    #[serde(rename = "CELEBRATION")]
    CELEBRATION,
    #[serde(rename = "CHARITY")]
    CHARITY,
    #[serde(rename = "CHILDREN")]
    CHILDREN,
    #[serde(rename = "COFFEE")]
    COFFEE,
    #[serde(rename = "DEBT_REPAYMENT")]
    DEBTREPAYMENT,
    #[serde(rename = "DIY")]
    DIY,
    #[serde(rename = "DRINKS")]
    DRINKS,
    #[serde(rename = "EATING_OUT")]
    EATINGOUT,
    #[serde(rename = "EDUCATION")]
    EDUCATION,
    #[serde(rename = "EMERGENCY")]
    EMERGENCY,
    #[serde(rename = "ENTERTAINMENT")]
    ENTERTAINMENT,
    #[serde(rename = "ESSENTIAL_SPEND")]
    ESSENTIALSPEND,
    #[serde(rename = "EXPENSES")]
    EXPENSES,
    #[serde(rename = "FAMILY")]
    FAMILY,
    #[serde(rename = "FITNESS")]
    FITNESS,
    #[serde(rename = "FUEL")]
    FUEL,
    #[serde(rename = "GAMBLING")]
    GAMBLING,
    #[serde(rename = "GAMING")]
    GAMING,
    #[serde(rename = "GARDEN")]
    GARDEN,
    #[serde(rename = "GENERAL")]
    GENERAL,
    #[serde(rename = "GIFTS")]
    GIFTS,
    #[serde(rename = "GROCERIES")]
    GROCERIES,
    #[serde(rename = "HOBBY")]
    HOBBY,
    #[serde(rename = "HOLIDAYS")]
    HOLIDAYS,
    #[serde(rename = "HOME")]
    HOME,
    #[serde(rename = "IMPULSE_BUY")]
    IMPULSEBUY,
    #[serde(rename = "INCOME")]
    INCOME,
    #[serde(rename = "INSURANCE")]
    INSURANCE,
    #[serde(rename = "INVESTMENTS")]
    INVESTMENTS,
    #[serde(rename = "LIFESTYLE")]
    LIFESTYLE,
    #[serde(rename = "MAINTENANCE_AND_REPAIRS")]
    MAINTENANCEANDREPAIRS,
    #[serde(rename = "MEDICAL")]
    MEDICAL,
    #[serde(rename = "MORTGAGE")]
    MORTGAGE,
    #[serde(rename = "NON_ESSENTIAL_SPEND")]
    NONESSENTIALSPEND,
    #[serde(rename = "PAYMENTS")]
    PAYMENTS,
    #[serde(rename = "PERSONAL_TRANSFERS")]
    PERSONALTRANSFERS,
    #[serde(rename = "PETS")]
    PETS,
    #[serde(rename = "PROJECTS")]
    PROJECTS,
    #[serde(rename = "RELATIONSHIPS")]
    RELATIONSHIPS,
    #[serde(rename = "RENT")]
    RENT,
    #[serde(rename = "SAVING")]
    SAVING,
    #[serde(rename = "SHOPPING")]
    SHOPPING,
    #[serde(rename = "SUBSCRIPTIONS")]
    SUBSCRIPTIONS,
    #[serde(rename = "TAKEAWAY")]
    TAKEAWAY,
    #[serde(rename = "TAXI")]
    TAXI,
    #[serde(rename = "TRANSPORT")]
    TRANSPORT,
    #[serde(rename = "TREATS")]
    TREATS,
    #[serde(rename = "WEDDING")]
    WEDDING,
    #[serde(rename = "WELLBEING")]
    WELLBEING,
    #[serde(rename = "NONE")]
    NONE,
    #[serde(rename = "REVENUE")]
    REVENUE,
    #[serde(rename = "OTHER_INCOME")]
    OTHERINCOME,
    #[serde(rename = "CLIENT_REFUNDS")]
    CLIENTREFUNDS,
    #[serde(rename = "INVENTORY")]
    INVENTORY,
    #[serde(rename = "STAFF")]
    STAFF,
    #[serde(rename = "TRAVEL")]
    TRAVEL,
    #[serde(rename = "WORKPLACE")]
    WORKPLACE,
    #[serde(rename = "REPAIRS_AND_MAINTENANCE")]
    REPAIRSANDMAINTENANCE,
    #[serde(rename = "ADMIN")]
    ADMIN,
    #[serde(rename = "MARKETING")]
    MARKETING,
    #[serde(rename = "BUSINESS_ENTERTAINMENT")]
    BUSINESSENTERTAINMENT,
    #[serde(rename = "INTEREST_PAYMENTS")]
    INTERESTPAYMENTS,
    #[serde(rename = "BANK_CHARGES")]
    BANKCHARGES,
    #[serde(rename = "OTHER")]
    OTHER,
    #[serde(rename = "FOOD_AND_DRINK")]
    FOODANDDRINK,
    #[serde(rename = "EQUIPMENT")]
    EQUIPMENT,
    #[serde(rename = "PROFESSIONAL_SERVICES")]
    PROFESSIONALSERVICES,
    #[serde(rename = "PHONE_AND_INTERNET")]
    PHONEANDINTERNET,
    #[serde(rename = "VEHICLES")]
    VEHICLES,
    #[serde(rename = "DIRECTORS_WAGES")]
    DIRECTORSWAGES,
    #[serde(rename = "VAT")]
    VAT,
    #[serde(rename = "CORPORATION_TAX")]
    CORPORATIONTAX,
    #[serde(rename = "SELF_ASSESSMENT_TAX")]
    SELFASSESSMENTTAX,
    #[serde(rename = "INVESTMENT_CAPITAL")]
    INVESTMENTCAPITAL,
    #[serde(rename = "TRANSFERS")]
    TRANSFERS,
    #[serde(rename = "LOAN_PRINCIPAL")]
    LOANPRINCIPAL,
    #[serde(rename = "PERSONAL")]
    PERSONAL,
    #[serde(rename = "DIVIDENDS")]
    DIVIDENDS,
}

impl Default for SpendingCategory {
    fn default() -> SpendingCategory {
        Self::BIKE
    }
}
/// Was this an inbound or outbound transaction
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
)]
pub enum NetDirection {
    #[serde(rename = "IN")]
    _IN,
    #[serde(rename = "OUT")]
    OUT,
}

impl Default for NetDirection {
    fn default() -> NetDirection {
        Self::_IN
    }
}
///
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
)]
pub enum Currency {
    #[serde(rename = "UNDEFINED")]
    UNDEFINED,
    #[serde(rename = "AED")]
    AED,
    #[serde(rename = "AFN")]
    AFN,
    #[serde(rename = "ALL")]
    ALL,
    #[serde(rename = "AMD")]
    AMD,
    #[serde(rename = "ANG")]
    ANG,
    #[serde(rename = "AOA")]
    AOA,
    #[serde(rename = "ARS")]
    ARS,
    #[serde(rename = "AUD")]
    AUD,
    #[serde(rename = "AWG")]
    AWG,
    #[serde(rename = "AZN")]
    AZN,
    #[serde(rename = "BAM")]
    BAM,
    #[serde(rename = "BBD")]
    BBD,
    #[serde(rename = "BDT")]
    BDT,
    #[serde(rename = "BGN")]
    BGN,
    #[serde(rename = "BHD")]
    BHD,
    #[serde(rename = "BIF")]
    BIF,
    #[serde(rename = "BMD")]
    BMD,
    #[serde(rename = "BND")]
    BND,
    #[serde(rename = "BOB")]
    BOB,
    #[serde(rename = "BOV")]
    BOV,
    #[serde(rename = "BRL")]
    BRL,
    #[serde(rename = "BSD")]
    BSD,
    #[serde(rename = "BTN")]
    BTN,
    #[serde(rename = "BWP")]
    BWP,
    #[serde(rename = "BYN")]
    BYN,
    #[serde(rename = "BYR")]
    BYR,
    #[serde(rename = "BZD")]
    BZD,
    #[serde(rename = "CAD")]
    CAD,
    #[serde(rename = "CDF")]
    CDF,
    #[serde(rename = "CHE")]
    CHE,
    #[serde(rename = "CHF")]
    CHF,
    #[serde(rename = "CHW")]
    CHW,
    #[serde(rename = "CLF")]
    CLF,
    #[serde(rename = "CLP")]
    CLP,
    #[serde(rename = "CNY")]
    CNY,
    #[serde(rename = "COP")]
    COP,
    #[serde(rename = "COU")]
    COU,
    #[serde(rename = "CRC")]
    CRC,
    #[serde(rename = "CUC")]
    CUC,
    #[serde(rename = "CUP")]
    CUP,
    #[serde(rename = "CVE")]
    CVE,
    #[serde(rename = "CZK")]
    CZK,
    #[serde(rename = "DJF")]
    DJF,
    #[serde(rename = "DKK")]
    DKK,
    #[serde(rename = "DOP")]
    DOP,
    #[serde(rename = "DZD")]
    DZD,
    #[serde(rename = "EGP")]
    EGP,
    #[serde(rename = "ERN")]
    ERN,
    #[serde(rename = "ETB")]
    ETB,
    #[serde(rename = "EUR")]
    EUR,
    #[serde(rename = "FJD")]
    FJD,
    #[serde(rename = "FKP")]
    FKP,
    #[serde(rename = "GBP")]
    GBP,
    #[serde(rename = "GEL")]
    GEL,
    #[serde(rename = "GHS")]
    GHS,
    #[serde(rename = "GIP")]
    GIP,
    #[serde(rename = "GMD")]
    GMD,
    #[serde(rename = "GNF")]
    GNF,
    #[serde(rename = "GTQ")]
    GTQ,
    #[serde(rename = "GYD")]
    GYD,
    #[serde(rename = "HKD")]
    HKD,
    #[serde(rename = "HNL")]
    HNL,
    #[serde(rename = "HRK")]
    HRK,
    #[serde(rename = "HTG")]
    HTG,
    #[serde(rename = "HUF")]
    HUF,
    #[serde(rename = "IDR")]
    IDR,
    #[serde(rename = "ILS")]
    ILS,
    #[serde(rename = "INR")]
    INR,
    #[serde(rename = "IQD")]
    IQD,
    #[serde(rename = "IRR")]
    IRR,
    #[serde(rename = "ISK")]
    ISK,
    #[serde(rename = "JMD")]
    JMD,
    #[serde(rename = "JOD")]
    JOD,
    #[serde(rename = "JPY")]
    JPY,
    #[serde(rename = "KES")]
    KES,
    #[serde(rename = "KGS")]
    KGS,
    #[serde(rename = "KHR")]
    KHR,
    #[serde(rename = "KMF")]
    KMF,
    #[serde(rename = "KPW")]
    KPW,
    #[serde(rename = "KRW")]
    KRW,
    #[serde(rename = "KWD")]
    KWD,
    #[serde(rename = "KYD")]
    KYD,
    #[serde(rename = "KZT")]
    KZT,
    #[serde(rename = "LAK")]
    LAK,
    #[serde(rename = "LBP")]
    LBP,
    #[serde(rename = "LKR")]
    LKR,
    #[serde(rename = "LRD")]
    LRD,
    #[serde(rename = "LSL")]
    LSL,
    #[serde(rename = "LTL")]
    LTL,
    #[serde(rename = "LYD")]
    LYD,
    #[serde(rename = "MAD")]
    MAD,
    #[serde(rename = "MDL")]
    MDL,
    #[serde(rename = "MGA")]
    MGA,
    #[serde(rename = "MKD")]
    MKD,
    #[serde(rename = "MMK")]
    MMK,
    #[serde(rename = "MNT")]
    MNT,
    #[serde(rename = "MOP")]
    MOP,
    #[serde(rename = "MRO")]
    MRO,
    #[serde(rename = "MRU")]
    MRU,
    #[serde(rename = "MUR")]
    MUR,
    #[serde(rename = "MVR")]
    MVR,
    #[serde(rename = "MWK")]
    MWK,
    #[serde(rename = "MXN")]
    MXN,
    #[serde(rename = "MXV")]
    MXV,
    #[serde(rename = "MYR")]
    MYR,
    #[serde(rename = "MZN")]
    MZN,
    #[serde(rename = "NAD")]
    NAD,
    #[serde(rename = "NGN")]
    NGN,
    #[serde(rename = "NIO")]
    NIO,
    #[serde(rename = "NOK")]
    NOK,
    #[serde(rename = "NPR")]
    NPR,
    #[serde(rename = "NZD")]
    NZD,
    #[serde(rename = "OMR")]
    OMR,
    #[serde(rename = "PAB")]
    PAB,
    #[serde(rename = "PEN")]
    PEN,
    #[serde(rename = "PGK")]
    PGK,
    #[serde(rename = "PHP")]
    PHP,
    #[serde(rename = "PKR")]
    PKR,
    #[serde(rename = "PLN")]
    PLN,
    #[serde(rename = "PYG")]
    PYG,
    #[serde(rename = "QAR")]
    QAR,
    #[serde(rename = "RON")]
    RON,
    #[serde(rename = "RSD")]
    RSD,
    #[serde(rename = "RUB")]
    RUB,
    #[serde(rename = "RUR")]
    RUR,
    #[serde(rename = "RWF")]
    RWF,
    #[serde(rename = "SAR")]
    SAR,
    #[serde(rename = "SBD")]
    SBD,
    #[serde(rename = "SCR")]
    SCR,
    #[serde(rename = "SDG")]
    SDG,
    #[serde(rename = "SEK")]
    SEK,
    #[serde(rename = "SGD")]
    SGD,
    #[serde(rename = "SHP")]
    SHP,
    #[serde(rename = "SLL")]
    SLL,
    #[serde(rename = "SOS")]
    SOS,
    #[serde(rename = "SRD")]
    SRD,
    #[serde(rename = "SSP")]
    SSP,
    #[serde(rename = "STD")]
    STD,
    #[serde(rename = "STN")]
    STN,
    #[serde(rename = "SVC")]
    SVC,
    #[serde(rename = "SYP")]
    SYP,
    #[serde(rename = "SZL")]
    SZL,
    #[serde(rename = "THB")]
    THB,
    #[serde(rename = "TJS")]
    TJS,
    #[serde(rename = "TMT")]
    TMT,
    #[serde(rename = "TND")]
    TND,
    #[serde(rename = "TOP")]
    TOP,
    #[serde(rename = "TRY")]
    _TRY,
    #[serde(rename = "TTD")]
    TTD,
    #[serde(rename = "TWD")]
    TWD,
    #[serde(rename = "TZS")]
    TZS,
    #[serde(rename = "UAH")]
    UAH,
    #[serde(rename = "UGX")]
    UGX,
    #[serde(rename = "USD")]
    USD,
    #[serde(rename = "USN")]
    USN,
    #[serde(rename = "USS")]
    USS,
    #[serde(rename = "UYI")]
    UYI,
    #[serde(rename = "UYU")]
    UYU,
    #[serde(rename = "UZS")]
    UZS,
    #[serde(rename = "VEF")]
    VEF,
    #[serde(rename = "VES")]
    VES,
    #[serde(rename = "VND")]
    VND,
    #[serde(rename = "VUV")]
    VUV,
    #[serde(rename = "WST")]
    WST,
    #[serde(rename = "XAF")]
    XAF,
    #[serde(rename = "XAG")]
    XAG,
    #[serde(rename = "XAU")]
    XAU,
    #[serde(rename = "XBA")]
    XBA,
    #[serde(rename = "XBB")]
    XBB,
    #[serde(rename = "XBC")]
    XBC,
    #[serde(rename = "XBD")]
    XBD,
    #[serde(rename = "XCD")]
    XCD,
    #[serde(rename = "XDR")]
    XDR,
    #[serde(rename = "XOF")]
    XOF,
    #[serde(rename = "XPD")]
    XPD,
    #[serde(rename = "XPF")]
    XPF,
    #[serde(rename = "XPT")]
    XPT,
    #[serde(rename = "XSU")]
    XSU,
    #[serde(rename = "XTS")]
    XTS,
    #[serde(rename = "XUA")]
    XUA,
    #[serde(rename = "XXX")]
    XXX,
    #[serde(rename = "YER")]
    YER,
    #[serde(rename = "ZAR")]
    ZAR,
    #[serde(rename = "ZMW")]
    ZMW,
    #[serde(rename = "ZWL")]
    ZWL,
}

impl Default for Currency {
    fn default() -> Currency {
        Self::UNDEFINED
    }
}
