/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// StandingOrderRecurrence : Recurrence rules of a standing order

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct StandingOrderRecurrence {
    /// Date that the first standing order payment should be made
    #[serde(rename = "startDate")]
    pub start_date: String,
    /// Frequency of which payments should be made
    #[serde(rename = "frequency")]
    pub frequency: Frequency,
    /// Interval of specified frequency on which payments should be made
    #[serde(
        rename = "interval",
        skip_serializing_if = "Option::is_none"
    )]
    pub interval: Option<i32>,
    /// Number of payments that should be made before standing order is stopped
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// Date on which to stop standing order
    #[serde(
        rename = "untilDate",
        skip_serializing_if = "Option::is_none"
    )]
    pub until_date: Option<String>,
}

impl StandingOrderRecurrence {
    /// Recurrence rules of a standing order
    pub fn new(
        start_date: String,
        frequency: Frequency,
    ) -> StandingOrderRecurrence {
        StandingOrderRecurrence {
            start_date,
            frequency,
            interval: None,
            count: None,
            until_date: None,
        }
    }
}

/// Frequency of which payments should be made
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
)]
pub enum Frequency {
    #[serde(rename = "DAILY")]
    DAILY,
    #[serde(rename = "WEEKLY")]
    WEEKLY,
    #[serde(rename = "MONTHLY")]
    MONTHLY,
    #[serde(rename = "YEARLY")]
    YEARLY,
}

impl Default for Frequency {
    fn default() -> Frequency {
        Self::DAILY
    }
}
