/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// StandingOrdersResponse : List of standing orders associated to an account holder

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct StandingOrdersResponse {
    #[serde(
        rename = "standingOrders",
        skip_serializing_if = "Option::is_none"
    )]
    pub standing_orders: Option<Vec<crate::models::StandingOrder>>,
}

impl StandingOrdersResponse {
    /// List of standing orders associated to an account holder
    pub fn new() -> StandingOrdersResponse {
        StandingOrdersResponse {
            standing_orders: None,
        }
    }
}
