/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// TaxLiabilityDeclarationCountry : Countries in which account holder has tax liabilities

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TaxLiabilityDeclarationCountry {
    /// Country code in ISO 3166-1 alpha-2. NB GB is the official country code for the UK. UK is not the officially assigned code, and so is not valid
    #[serde(rename = "countryCode")]
    pub country_code: String,
    /// Tax identification number
    #[serde(
        rename = "taxIdentificationNumber",
        skip_serializing_if = "Option::is_none"
    )]
    pub tax_identification_number: Option<String>,
}

impl TaxLiabilityDeclarationCountry {
    /// Countries in which account holder has tax liabilities
    pub fn new(country_code: String) -> TaxLiabilityDeclarationCountry {
        TaxLiabilityDeclarationCountry {
            country_code,
            tax_identification_number: None,
        }
    }
}
