/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// TaxDeclarationActions : Tax Declaration status

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TaxDeclarationActions {
    /// Tax Declaration onboarding status
    #[serde(
        rename = "status",
        skip_serializing_if = "Option::is_none"
    )]
    pub status: Option<Status>,
}

impl TaxDeclarationActions {
    /// Tax Declaration status
    pub fn new() -> TaxDeclarationActions {
        TaxDeclarationActions { status: None }
    }
}

/// Tax Declaration onboarding status
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
)]
pub enum Status {
    #[serde(rename = "AWAITING_UPLOAD")]
    AWAITINGUPLOAD,
    #[serde(rename = "READY_FOR_REVIEW")]
    READYFORREVIEW,
    #[serde(rename = "NOT_REQUIRED")]
    NOTREQUIRED,
}

impl Default for Status {
    fn default() -> Status {
        Self::AWAITINGUPLOAD
    }
}
