/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// TermsAcceptance : Users acceptance of a specific starling policy document

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TermsAcceptance {
    /// The policy document which has been accepted
    #[serde(rename = "policyDocument")]
    pub policy_document: PolicyDocument,
    /// The version of the policy document which has been accepted
    #[serde(rename = "version")]
    pub version: i32,
    /// Was policy document accepted
    #[serde(rename = "termsAccepted")]
    pub terms_accepted: bool,
    /// The date on which the policy document was accepted
    #[serde(rename = "acceptanceDate")]
    pub acceptance_date: String,
}

impl TermsAcceptance {
    /// Users acceptance of a specific starling policy document
    pub fn new(
        policy_document: PolicyDocument,
        version: i32,
        terms_accepted: bool,
        acceptance_date: String,
    ) -> TermsAcceptance {
        TermsAcceptance {
            policy_document,
            version,
            terms_accepted,
            acceptance_date,
        }
    }
}

/// The policy document which has been accepted
#[derive(
    Clone,
    Copy,
    Debug,
    Eq,
    PartialEq,
    Ord,
    PartialOrd,
    Hash,
    Serialize,
    Deserialize,
)]
pub enum PolicyDocument {
    #[serde(rename = "ACCOUNT_TERMS")]
    ACCOUNTTERMS,
    #[serde(rename = "STARLING_PRIVACY_POLICY")]
    STARLINGPRIVACYPOLICY,
    #[serde(rename = "FSCS_INFORMATION")]
    FSCSINFORMATION,
}

impl Default for PolicyDocument {
    fn default() -> PolicyDocument {
        Self::ACCOUNTTERMS
    }
}
