/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// TopUpRequestV2 : Request to make an immediate transfer into a savings goal

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TopUpRequestV2 {
    #[serde(rename = "amount")]
    pub amount: Box<crate::models::CurrencyAndAmount>,
}

impl TopUpRequestV2 {
    /// Request to make an immediate transfer into a savings goal
    pub fn new(
        amount: crate::models::CurrencyAndAmount,
    ) -> TopUpRequestV2 {
        TopUpRequestV2 {
            amount: Box::new(amount),
        }
    }
}
