/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// UpdateOnboardingPersonalInfoRequest : Request to update the personal information for an individual that's onboarding. Only fields to be updated need to be supplied, if unchanged they may be null.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateOnboardingPersonalInfoRequest {
    /// Account holder's first name
    #[serde(
        rename = "firstName",
        skip_serializing_if = "Option::is_none"
    )]
    pub first_name: Option<String>,
    /// Account holder's middle name
    #[serde(
        rename = "middleName",
        skip_serializing_if = "Option::is_none"
    )]
    pub middle_name: Option<String>,
    /// Account holder's last name
    #[serde(
        rename = "lastName",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_name: Option<String>,
    /// Account holder's date of birth
    #[serde(
        rename = "dateOfBirth",
        skip_serializing_if = "Option::is_none"
    )]
    pub date_of_birth: Option<String>,
}

impl UpdateOnboardingPersonalInfoRequest {
    /// Request to update the personal information for an individual that's onboarding. Only fields to be updated need to be supplied, if unchanged they may be null.
    pub fn new() -> UpdateOnboardingPersonalInfoRequest {
        UpdateOnboardingPersonalInfoRequest {
            first_name: None,
            middle_name: None,
            last_name: None,
            date_of_birth: None,
        }
    }
}
