/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateEmailRequest {
    /// The new email address for the account holder
    #[serde(rename = "email")]
    pub email: String,
}

impl UpdateEmailRequest {
    pub fn new(email: String) -> UpdateEmailRequest {
        UpdateEmailRequest { email }
    }
}
