/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// UpdateStandingOrderResponse : Response after attempting to update a standing order

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateStandingOrderResponse {
    /// The uid of the updated payment order created by the standing order. N.B. this will not be the uid of any payment which is created by the standing order. If the recurrence rule is updated, this payment order uid will be different from the original one
    #[serde(
        rename = "paymentOrderUid",
        skip_serializing_if = "Option::is_none"
    )]
    pub payment_order_uid: Option<String>,
}

impl UpdateStandingOrderResponse {
    /// Response after attempting to update a standing order
    pub fn new() -> UpdateStandingOrderResponse {
        UpdateStandingOrderResponse {
            payment_order_uid: None,
        }
    }
}
