/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// ValidMobilePhoneCountries : The valid countries from where a mobile number can originate from

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ValidMobilePhoneCountries {
    /// ISO country codes where a mobile number can originate from
    #[serde(
        rename = "validCountries",
        skip_serializing_if = "Option::is_none"
    )]
    pub valid_countries: Option<Vec<String>>,
}

impl ValidMobilePhoneCountries {
    /// The valid countries from where a mobile number can originate from
    pub fn new() -> ValidMobilePhoneCountries {
        ValidMobilePhoneCountries {
            valid_countries: None,
        }
    }
}
