/*
 * Starling Bank API
 *
 * OpenAPI specification for the Starling Bank Public API.  For more information visit: https://developer.starlingbank.com/docs
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// WithdrawalRequestV2 : Request to withdraw money from a savings goal.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WithdrawalRequestV2 {
    #[serde(rename = "amount")]
    pub amount: Box<crate::models::CurrencyAndAmount>,
}

impl WithdrawalRequestV2 {
    /// Request to withdraw money from a savings goal.
    pub fn new(
        amount: crate::models::CurrencyAndAmount,
    ) -> WithdrawalRequestV2 {
        WithdrawalRequestV2 {
            amount: Box::new(amount),
        }
    }
}
